### PR TITLE
Issue #301 - wrong transparency when drawing image (regression from PR #224)

### LINKED ISSUE #301: Regression drawing image arising from fix to #185 and other regressions in Image class
Windows only.

There have been a few  changes to the way transparency is handled in the `Image` class on Windows from @jonathan-meier recently. However, we were left with a bug that caused problems that was apparently fixed here with https://github.com/eclipse-platform/eclipse.platform.swt/issues/185

Unfortunately this fix has caused yet another bug which now makes our RCP application broken when targetted with the latest SWT version.

The regression is caused by the fix in 8def011fdd013543a5ea5513dacef5914c3c8662 - however the underlying cause is somewhere deeper than that arising from previous changes to `Image` class on Windows

I have put together a snippet that shows the problem (see later post)

If you run the snippet with a version of SWT prior to 8def011fdd013543a5ea5513dacef5914c3c8662 a red box should be drawn:

correct

But running the snippet with a version of SWT after 8def011fdd013543a5ea5513dacef5914c3c8662 gives a wrong colored image:

incorrect

### PR DESCRIPTION
**Pull request by jonathan-meier**
Fixes #301.

### CODE REVIEW

**Comment by vogella** [comment]
@SyntevoAlex can you reiview and merge this one?

**Comment by SyntevoAlex** [comment]
I could have a look, hopefully today or tomorrow.

**Review by niraj-modi — APPROVED** [review]
This patch works as expected, tested with below snippet:
https://github.com/eclipse-platform/eclipse.platform.swt/issues/301#issuecomment-1209832523

**Comment by Phillipus** [comment]
Thanks, everyone! 👍

**Pull request merged**
