### PR TITLE
Test implemention of #858 suggested method

### PR DESCRIPTION
**Pull request by the-snowwhite**
~~This is a draft. Do not merge.~~
Update:
Ready for review please look at #884

This is a test that implements #858 and adds #879 as payload

The purpose is to check if a Maintenance branch
would be able to deliver build artifacts suited
for testing bugfix purposes (during a freeze).

It will be implemented as 1 + 3 commits

The first one enables building by emulating dependabot[bot]
The idea is to setup a state that emulates a bugfix patch.

As there are needed functional changes for the build to succeed
The last 3 commits are cherry picked from the [wayland_qt_clipboard_fix](https://github.com/eclipse-platform/eclipse.platform.swt/compare/master...the-snowwhite:eclipse.platform.swt:wayland_qt_paste_copy_fix_R4.29)
merged recently.
Update
Test is concluded successfully, however:

>PRs are not a place for sandbox work, please work on your own branch and submit PRs only when you intend your code to be merged, as a regular PR is ready, as a draft if you need further collaboration to happen before the code is ready.

I think I placed this Draft_PR the wrong place/way.
Where is there a place for testing adding new functionality under a freeze ?

Final update for review.
Is this a bug-fix or a new feature !
What would the consequences of being able to merge this commit in the M3-->RCx period be for 2023-09 users
I an ideal world ?

### CODE REVIEW

**Comment by the-snowwhite** [comment]
Hmmm
This build did succeed without any errors
However my local build did not so:
Is there something wrong with my local build config ?
I can analyze this buy running the commands from the build console log from this build.
Or 
> Looking in the Jenkinsfile will show you concrete commands to build SWT

try to figure out what a jenkinsfile is and what the exact filename is.

**Comment by the-snowwhite** [comment]
OK
I managed to reduce the console log to exactly 256 lines by hand.
That should contain the info to fix my local build errors and warnings.

**Comment by the-snowwhite** [comment]
https://ci.eclipse.org/releng/job/eclipse.platform.swt/view/change-requests/job/PR-890/1/flowGraphTable/
is handy also.

**Comment by the-snowwhite** [comment]
OK the local build now completes without any FAILURES.
`~/git/eclipse.platform.swt$ mvn dependency:analyze`
seemed to fix that.
and only using the build commands:

    ~/git/eclipse.platform.swt$ cd ~/git/eclipse.platform.swt.binaries
    ~/git/eclipse.platform.swt$ mvn install --batch-mode -Pbuild-individual-bundles -DforceContextQualifier=zzz -Dcompare-version-with-baselines.skip=true -Dmaven.compiler.failOnWarning=true
    ~/git/eclipse.platform.swt$ cd ~/git/eclipse.platform.swt
    ~/git/eclipse.platform.swt$ mvn clean verify --batch-mode -DforkCount=0 -Dcompare-version-with-baselines.skip=false -Dmaven.compiler.failOnWarning=true -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true

Now just to solve the warnings

    :~/git/eclipse.platform.swt$ mvn clean verify --batch-mode -Dmaven.plugin.validation=VERBOSE -DforkCount=0 -Dcompare-version-with-baselines.skip=false -Dmaven.compiler.failOnWarning=true -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true

    [WARNING]
    [WARNING] Plugin validation issues were detected in 2 plugin(s)
    [WARNING]
    [WARNING]  * org.apache.maven.plugins:maven-site-plugin:3.12.1
    [WARNING]   Plugin issue(s):
    [WARNING]    * Plugin depends on the deprecated Maven 2.x compatibility layer, which may not be supported in Maven 4.x
    [WARNING]
    [WARNING]  * org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.2
    [WARNING]   Declared at location(s):
    [WARNING]    * org.eclipse:eclipse-platform-parent:4.29.0-SNAPSHOT (/home/mib/.m2/repository/org/eclipse/eclipse-platform-parent/4.29.0-SNAPSHOT/eclipse-platform-parent-4.29.0-SNAPSHOT.pom) @ line 371
    [WARNING]   Used in module(s):
    [WARNING]    * eclipse.platform.swt:eclipse.platform.swt:4.29.0-SNAPSHOT (pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt:3.124.101-SNAPSHOT (bundles/org.eclipse.swt/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.fragments.localbuild:3.105.0-SNAPSHOT (local-build/org.eclipse.swt.fragments.localbuild/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.tools.base:3.107.400-SNAPSHOT (bundles/org.eclipse.swt.tools.base/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.tools.spies:3.109.100-SNAPSHOT (bundles/org.eclipse.swt.tools.spies/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.tools:3.110.100-SNAPSHOT (bundles/org.eclipse.swt.tools/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.examples:3.108.100-SNAPSHOT (examples/org.eclipse.swt.examples/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.examples.browser.demos:3.108.100-SNAPSHOT (examples/org.eclipse.swt.examples.browser.demos/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.examples.launcher:3.108.100-SNAPSHOT (examples/org.eclipse.swt.examples.launcher/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.examples.ole.win32:3.108.100-SNAPSHOT (examples/org.eclipse.swt.examples.ole.win32/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.examples.views:3.108.100-SNAPSHOT (examples/org.eclipse.swt.examples.views/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.tests:3.107.100-SNAPSHOT (tests/org.eclipse.swt.tests/pom.xml)
    [WARNING]    * org.eclipse.swt.tools.feature:org.eclipse.swt.tools.feature:3.109.100-SNAPSHOT (features/org.eclipse.swt.tools.feature/pom.xml)
    [WARNING]    * org.eclipse.swt:org.eclipse.swt.tests.gtk:3.109.0-SNAPSHOT (tests/org.eclipse.swt.tests.gtk/pom.xml)
    [WARNING]   Mojo issue(s):
    [WARNING]    * Mojo tycho-p2-extras:compare-version-with-baselines (org.eclipse.tycho.plugins.p2.extras.CompareWithBaselineMojo)
    [WARNING]      - Parameter 'comparator' is read-only, must not be used in configuration
    [WARNING]
    [WARNING]
    [WARNING] Fix reported issues by adjusting plugin configuration or by upgrading above listed plugins. If no upgrade available, please notify plugin maintainers about reported issues.
    [WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
    [WARNING]



No

**Comment by the-snowwhite** [comment]
OK
20:53:25  Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)
20:53:25  Maven home: /opt/tools/apache-maven/latest

and:
    
    ~/git/eclipse.platform.swt$ mvn -version
    Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
    Maven home: /opt/maven
    Java version: 17.0.8.1, vendor: Eclipse Adoptium, runtime: /home/mib/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.8.v20230831-1047/jre
    Default locale: en_DK, platform encoding: UTF-8
    OS name: "linux", version: "6.2.0-36-generic", arch: "amd64", family: "unix"

**Comment by the-snowwhite** [comment]
update maven to 2.9.3

    ~$ wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.3/apache-maven-3.9.3-bin.tar.gz -P /tmp
    sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt
    sudo rm /opt/maven
    sudo ln -s /opt/apache-maven-3.9.3 /opt/maven

**Comment by the-snowwhite** [comment]
Yes no warnings.

Onto --> https://github.com/eclipse-platform/eclipse.platform.swt/discussions/858#discussioncomment-7542214
Step 9.

**Comment by the-snowwhite** [comment]
Yes no warnings.

Onto --> https://github.com/eclipse-platform/eclipse.platform.swt/discussions/858#discussioncomment-7542214
Step 9.

Clipboard functionality validated with both local and automated build.

With the downloaded files the about plugins view says:

    Eclipse.org	Standard Widget Toolkit	3.124.100.v20230825-1346	org.eclipse.swt
    Eclipse.org	Standard Widget Toolkit for GTK	3.124.200.zzz	org.eclipse.swt.gtk.linux.x86_64

With the local files the about plugins view says:

    Eclipse.org	Standard Widget Toolkit	3.124.100.v20230825-1346	org.eclipse.swt
    Eclipse.org	Standard Widget Toolkit for GTK	3.124.100.zzz	org.eclipse.swt.gtk.linux.x86_64

**Comment by the-snowwhite** [comment]
zzz

**Comment by the-snowwhite** [comment]
OK
I have now tested steps 9, 10, 11 from https://github.com/eclipse-platform/eclipse.platform.swt/discussions/858#discussioncomment-7542214
on my former workstation.

It is only needed to copy 2 files not 3.
afterwards the about-->installation Details-->Plug ins (search swt) says:

    Eclipse.org	Standard Widget Toolkit for GTK	3.124.200.zzz	org.eclipse.swt.gtk.linux.x86_64

And Clipboard works both ways between Eclipse and Kate in a kde session running on a standard Kde Neon (ubuntu 22.04 LTS based) also on my old Eclipse PHP installation where the plugins are in the Eclipse installation folder (updated to 2023-09).

**Comment by mickaelistria** [comment]
I have a coarser-grain question here: what do you expect by trying to backport the change to 4.29 branch? The Eclipse project doesn't build a 4.29.x branch any more, so even if this is merged, then it wouldn't make the output available in any 4.29.x binary. Why not just using 4.30 ?

**Comment by the-snowwhite** [comment]
I have an elder active scientist I'm supporting and he is unable to use 4.30 before the official release.
Being able to create a bugfix for him could avoid disruptions of his work until the 2023-12 PHP is rolled out. 
I didn't understand the value of creating a draft instead of do not merge commits.
I also did not know that Eclipse SWT has abandoned bugfix patches which is what I think could have led to a merge.

**Pull request closed without merging**
