### PR TITLE
Fix classpath not found on macOS aarch64

### PR DESCRIPTION
**Pull request by Phillipus**
- Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/774

### CODE REVIEW

**Review by jukzi — DISMISSED** [review]
fix all references to the classpath_cocoa
image

**Comment by jukzi** [comment]
@merks may be that also needs some adjustment to thee OOmphed setup?

**Comment by merks** [comment]
> @merks may be that also needs some adjustment to thee OOmphed setup?

Yes, I noticed this and mentioned that here:

https://github.com/eclipse-platform/eclipse.platform.swt/issues/774#issuecomment-1685819066

I'm concerned that we aren't being consistent across platforms such that computing the name of the file to be renamed will be tricky.  I.e., in some cases the os.arch is considered and in some cases not...

**Comment by merks** [comment]
FYI, these are the tasks that will need attention;
```
<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:setup="http://www.eclipse.org/oomph/setup/1.0">
  <setup:ResourceCopyTask
      excludedTriggers="BOOTSTRAP"
      sourceURL="${github.clone.platform.swt.location|uri}/bundles/org.eclipse.swt/.classpath_${osgi.ws}"
      targetURL="${github.clone.platform.swt.location|uri}/bundles/org.eclipse.swt/.classpath"/>
  <setup:ResourceCopyTask
      excludedTriggers="BOOTSTRAP"
      sourceURL="${github.clone.platform.swt.location|uri}/examples/org.eclipse.swt.snippets/.classpath_${osgi.ws}"
      targetURL="${github.clone.platform.swt.location|uri}/examples/org.eclipse.swt.snippets/.classpath"/>
</xmi:XMI>

```
This suggests that the corresponding change to the snippets set of classpaths needs attention.  It also suggest that while mac has a special classpath file for each of the two supported architectures, Linux and Windows do not.   Of course I can work around such non-orthogonal things, but inconsistencies tend to bite again later...

**Comment by Phillipus** [comment]
> fix all references to the classpath_cocoa image

Force pushed this PR with changes and created https://github.com/eclipse-platform/www.eclipse.org-swt/pull/10

**Comment by Phillipus** [comment]
> I'm concerned that we aren't being consistent across platforms such that computing the name of the file to be renamed will be tricky. I.e., in some cases the os.arch is considered and in some cases not...

Alternate proposal:

https://github.com/eclipse-platform/eclipse.platform.swt/issues/774#issuecomment-1685865210

**Review by jukzi — COMMENTED** [review]
looks better, but i guess OOmph needs changes. https://github.com/eclipse-platform/eclipse.platform.swt/pull/776#issuecomment-1685838538

**Comment by Phillipus** [comment]
> I still don’t see the additional classpath file for the snippets, i.e., the one the readme in that project describes. Maybe just a problem looking on my iPhone.

[Here](url) - but does that need renaming or changing?

**Comment by Phillipus** [comment]
I'm not even sure what those .classpath files are for in https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets

**Comment by Phillipus** [comment]
So is https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/Readme.md referring to the .classpath files in the `org.eclipse.swt.snippets` directory or the root `eclipse.platform.swt` directory? If the first, then no change is needed in `Readme.md`

**Comment by merks** [comment]
> So is https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/Readme.md referring to the .classpath files in the `org.eclipse.swt.snippets` directory or the root `eclipse.platform.swt` directory? If the first, then no change is needed in `Readme.md` because the `.classpath_cocoa` file works on x86_64 and aarch64.

Indeed, I think it's only to omit certain snippets that are  os-specific to avoid compile errors in the workspace.   So forget my concern about that!

**Comment by Phillipus** [comment]
> > So is https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/Readme.md referring to the .classpath files in the `org.eclipse.swt.snippets` directory or the root `eclipse.platform.swt` directory? If the first, then no change is needed in `Readme.md` because the `.classpath_cocoa` file works on x86_64 and aarch64.
> 
> Indeed, I think it's only to omit certain snippets that are os-specific to avoid compile errors in the workspace. So forget my concern about that!

OK, I reverted that `Readme.md` back to the original and force pushed the PR.

**Comment by Phillipus** [comment]
Can this be merged now, or is there something missing?

**Comment by iloveeclipse** [comment]
> Can this be merged now, or is there something missing?

I haven't followed whole discussion, but if you are confident in the change, feel free to rebase and merge.

**Comment by Phillipus** [comment]
> > Can this be merged now, or is there something missing?
> 
> I haven't followed whole discussion, but if you are confident in the change, feel free to rebase and merge.

I can't merge as I'm not a committer.

**Comment by iloveeclipse** [comment]
@merks : I see you have commented here and on original issue, please could you review & merge PR if it is in a state that satisfies everyone.

**Pull request merged**
