### PR TITLE
Revert "Correct GC offset calculation #788"

### PR DESCRIPTION
**Pull request by Phillipus**
- This reverts commit 657fffb389fdb781db1d18331a31cd104858c4e5.
- This created a regression on Mac
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1067

### CODE REVIEW

**Comment by Phillipus** [comment]
Can this be merged for 4.31? @iloveeclipse @merks

**Comment by iloveeclipse** [comment]
I agree that the revert for 4.31 is the right thing.

**Comment by iloveeclipse** [comment]
@akurtakov : OK from you too?

**Comment by akurtakov** [comment]
Reproduced the issue - and the fact that the revert fixes is. PMC approved!

**Comment by Phillipus** [comment]
> Reproduced the issue - and the fact that the revert fixes is. PMC approved!

If approved, who merges? Is it me?

**Comment by akurtakov** [comment]
> > Reproduced the issue - and the fact that the revert fixes is. PMC approved!
> 
> If approved, who merges? Is it me?

Yes, you have the approvals so if you're ready - push.

**Comment by Phillipus** [comment]
> > > Reproduced the issue - and the fact that the revert fixes is. PMC approved!
> > 
> > 
> > If approved, who merges? Is it me?
> 
> Yes, you have the approvals so if you're ready - push.

Thanks. Done.

**Pull request merged**
