### PR TITLE
Added an option to overrule the last file dialog location on Windows #466

### PR DESCRIPTION
**Pull request by deepika-u**

### CODE REVIEW

**Review by niraj-modi — APPROVED** [review]
Verified this PR in peer review.

**Comment by niraj-modi** [comment]
@deepika-u 
You need to sign the Eclipse ECA, before we can merge.

**Comment by deepika-u** [comment]
I have signed the ECA now. Thanks.

**Comment by deepika-u** [comment]
Test cases i tried are as below ::
Via Snippet72 :
1. Set a valid filterPath(say for example "c:\\")
2. Set an invalid filterPath(say for example "c:\\@123")
3. Set filterPath to space(filterPath = " ")
4. Set filterPath to null(filterPath = null)
5. filterPath not set.
6. Set valid path then immediately set to null, then test.
7. Set to null then immediately set to valid path, then test.

General testing :
8. Windows > Preferences > User Libraries > Import > Browse > select some jar file(by changing *.*), open. Now Browse again and you'll notice path is remembered now.

The same fix is now available in RC1.

**Comment by Mailaender** [comment]
You did not close https://bugs.eclipse.org/bugs/show_bug.cgi?id=577190 on purpose?

**Comment by HannesWell** [comment]
> You did not close https://bugs.eclipse.org/bugs/show_bug.cgi?id=577190 on purpose?

Please note that Bugzilla is not used actively anymore to track issues in Eclipse top-level project's like SWT. While occasionally some issues are still updated Bugzilla will become read-only soon.

**Pull request merged**
