### PR TITLE
Make SWT tests fragment.

### PR DESCRIPTION
**Pull request by akurtakov**
Effort to reduce test failures as seen in
https://github.com/eclipse-platform/eclipse.platform.swt/issues/232 .

### CODE REVIEW

**Comment by akurtakov** [comment]
Unrelated and long standing test failures.

**Comment by SyntevoAlex** [comment]
Is it expected that you didn't change `Bundle-Localization: plugin` and didn't change platform-specific test projects' manifests?

**Comment by akurtakov** [comment]
Platform specific test projects contain only manually executed tests AFAICT so no need to do it to fix the test failure. 
Bundle-Localization just points to the properties file to use for localizations so I think waiting to see that tests run before renaming plugin.properties might be best.

**Comment by SyntevoAlex** [comment]
OK, thanks for working on it!

**Pull request merged**
