### PR TITLE
Copy HTML line fragment without block levels. fixes #593

### LINKED ISSUE #593: Copy formatted text adds extra line(s) and format
**Describe the bug**
STRG+C a text without linebreaks from an editor
STRG+V into microsoft word or Teams => pastes copied text + one or even two newlines (NOK!)
STRG+V  into notepad++ => pastes only the copied text (OK)
STRG+SHIFT+V into microsoft word or Teams => pastes only the copied text (OK)

It's also not helpfull that the whole format is copied at all since the format depends on the current selection -> the copied text is shown ontop of light blue background, only because it was the selected line. 

**To Reproduce**
copy "main" from "public static void main(String[] args)" and paste it with format:
image

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [x] Windows
- - [x] Linux
- - [?] macOS 

**Version since**
first recognized with 2022-12

**Workaround**
paste without format (STRG+SHIFT+V)

### PR DESCRIPTION
**Pull request by jukzi**
Does not add additional newline when pasting words to Teams/Word.

### CODE REVIEW

**Comment by jukzi** [comment]
@akurtakov @laeubi  can you help with this tycho error?
```
constituent[37]: file:/C:/ProgramData/chocolatey/lib/maven/apache-maven-3.8.7/lib/wagon-file-3.5.3.jarException in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/synccontext/SyncContextFactory
	at org.eclipse.tycho.core.resolver.MavenTargetLocationFactory.resolveTargetDefinitionContent(MavenTargetLocationFactory.java:53)
	at org.eclipse.tycho.p2resolver.TargetDefinitionResolver.resolveContentWithExceptions(TargetDefinitionResolver.java:172)
	at org.eclipse.tycho.p2resolver.TargetDefinitionResolver.resolveContent(TargetDefinitionResolver.java:102)
	at org.eclipse.tycho.p2resolver.TargetDefinitionResolverService.resolveFromArguments(TargetDefinitionResolverService.java:93)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.tycho.p2resolver.TargetDefinitionResolverService.getTargetDefinitionContent(TargetDefinitionResolverService.java:68)
	at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.resolveTargetDefinitions(TargetPlatformFactoryImpl.java:214)
	at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:164)
	at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:137)
	at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:88)
	at org.eclipse.tycho.p2resolver.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:71)
	at org.eclipse.tycho.p2resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:205)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:101)
	at org.eclipse.tycho.core.maven.TychoProjectExecutionListener.beforeProjectLifecycleExecution(TychoProjectExecutionListener.java:108)
	at org.apache.maven.lifecycle.internal.CompoundProjectExecutionListener.beforeProjectLifecycleExecution(CompoundProjectExecutionListener.java:52)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:114)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:298)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.synccontext.SyncContextFactory
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 33 more

```

**Comment by akurtakov** [comment]
Build has to run with Maven 3.9.x. I'll try to figure this one out.

**Comment by akurtakov** [comment]
Working on it in https://github.com/eclipse-platform/eclipse.platform.swt/pull/695

**Comment by akurtakov** [comment]
GHA builds will run now but tests fail. I can't spend more time on this one now, as long as Jenkins works it's fine by me. Hopefully someone else lands a hand to fix tests too.

**Comment by jukzi** [comment]
ignoring unrelated random fails:
```
Test_org_eclipse_swt_dnd_DND.testImageTransfer
Test_org_eclipse_swt_custom_StyledText.test_caretSizeAndPositionVariableGlyphMetrics
```

**Pull request merged**
