### PR TITLE
[Build] Run SWT native binary build in GH workflows

### PR DESCRIPTION
**Pull request by HannesWell**
This allows to test changes in the natives in verification builds on all platforms and not only on Linux because Jenkins re-builds the binaries.

### CODE REVIEW

**Comment by HannesWell** [comment]
Only fails on Linux due to missing GTK headers, for all other platforms the GH runners have the necessary prerequisites installed. Looks like they have to be installed explicitly.:
```
[INFO]      [exec] -e Cairo found, compiling SWT support for the cairo graphics library.
[INFO]      [exec] -e jni.h found
[INFO]      [exec] -e libjawt.so found, the SWT/AWT integration library will be compiled.
[INFO]      [exec] -e Building SWT/GTK+ for Architectures: linux x86_64
[INFO]      [exec] -e Building GTK3 bindings:
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror -c swt.c
[INFO]      [exec] Package gtk+-3.0 was not found in the pkg-config search path.
[INFO]      [exec] Perhaps you should add the directory containing `gtk+-3.0.pc'
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror   -c -o c.o c.cto the PKG_CONFIG_PATH environment variable
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror   -c -o c_stats.o c_stats.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -DUSE_ASSEMBLER -c callback.c
[INFO]      [exec] No package 'gtk+-3.0' found
[INFO]      [exec] 
[INFO]      [exec] Package gtk+-unix-print-3.0 was not found in the pkg-config search path.
[INFO]      [exec] Perhaps you should add the directory containing `gtk+-unix-print-3.0.pc'
[INFO]      [exec] to the PKG_CONFIG_PATH environment variable
[INFO]      [exec] No package 'gtk+-unix-print-3.0' found
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-gtk-4964r6.so swt.o c.o c_stats.o callback.o
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c os.c
[INFO]      [exec] -e *** GTK3 Build failed, aborting further actions..
[INFO]      [exec] Package gtk+-3.0 was not found in the pkg-config search path.
[INFO]      [exec] Perhaps you should add the directory containing `gtk+-3.0.pc'
[INFO]      [exec] to the PKG_CONFIG_PATH environment variable
[INFO]      [exec] No package 'gtk+-3.0' found
[INFO]      [exec] Package gtk+-unix-print-3.0 was not found in the pkg-config search path.
[INFO]      [exec] Perhaps you should add the directory containing `gtk+-unix-print-3.0.pc'
[INFO]      [exec] to the PKG_CONFIG_PATH environment variable
[INFO]      [exec] No package 'gtk+-unix-print-3.0' found
[INFO]      [exec] In file included from os_structs.h:19,
[INFO]      [exec]                  from os.c:20:
[INFO]      [exec] os.h:30:10: fatal error: gtk/gtk.h: No such file or directory
[INFO]      [exec]    30 | #include <gtk/gtk.h>
[INFO]      [exec]       |          ^~~~~~~~~~~
[INFO]      [exec] compilation terminated.
[INFO]      [exec] make: *** [make_linux.mak:144: os.o] Error 1
```

**Comment by HannesWell** [comment]
> Only fails on Linux due to missing GTK headers, for all other platforms the GH runners have the necessary prerequisites installed. Looks like they have to be installed explicitly.:

@akurtakov can you tell about an elegant way to make the GTK headers available in GH action runners?

**Comment by laeubi** [comment]
@HannesWell see here where things are installed for linux:

https://github.com/eclipse-platform/eclipse.platform.swt/blob/7e5d9895cacefe5584ad44b58252bf405a3276af/.github/workflows/maven.yml#L42

I would assume something like `libgtk-3-dev` is needed.

**Comment by HannesWell** [comment]
Thanks for the hint!
> I would assume something like `libgtk-3-dev` is needed.

Yes, I found the same when searching the internet. Lets see if this works.

**Comment by HannesWell** [comment]
We got one step further, but it looks like GLU is still missing. Will test if installing `freeglut3-dev` helps.
```
[INFO]      [exec] -e Cairo found, compiling SWT support for the cairo graphics library.
[INFO]      [exec] -e jni.h found
[INFO]      [exec] -e libjawt.so found, the SWT/AWT integration library will be compiled.
[INFO]      [exec] -e Building SWT/GTK+ for Architectures: linux x86_64
[INFO]      [exec] -e Building GTK3 bindings:
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror -c swt.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror   -c -o c.o c.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror   -c -o c_stats.o c_stats.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -DUSE_ASSEMBLER -c callback.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-gtk-4964r6.so swt.o c.o c_stats.o callback.o
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c os.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c os_structs.c 
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c os_custom.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c os_stats.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c gtk3.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c gtk3_stats.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c gtk3_structs.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-pi3-gtk-4964r6.so swt.o os.o os_structs.o os_custom.o os_stats.o gtk3.o gtk3_stats.o gtk3_structs.o `pkg-config --libs-only-L gtk+-3.0 gthread-2.0` -L/usr/X11R6/lib64 -L/usr/X11R6/lib -lgtk-3 -lgdk-3 -lcairo -lgthread-2.0
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags atk gtk+-3.0 gtk+-unix-print-3.0` -c atk.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags atk gtk+-3.0 gtk+-unix-print-3.0` -c atk_structs.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags atk gtk+-3.0 gtk+-unix-print-3.0` -c atk_custom.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags atk gtk+-3.0 gtk+-unix-print-3.0` -c atk_stats.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-atk-gtk-4964r6.so swt.o atk.o atk_structs.o atk_custom.o atk_stats.o `pkg-config --libs-only-L atk` -latk-1.0 
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror  -c glx.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror  -c glx_structs.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror  -c glx_stats.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-glx-gtk-4964r6.so swt.o glx.o glx_structs.o glx_stats.o -lGL -lGLU -lm
[INFO]      [exec] -e *** GTK3 Build failed, aborting further actions..
[INFO]      [exec] /usr/bin/ld: cannot find -lGLU: No such file or directory
[INFO]      [exec] collect2: error: ld returned 1 exit status
[INFO]      [exec] make: *** [make_linux.mak:232: libswt-glx-gtk-4964r6.so] Error 1
```

**Comment by HannesWell** [comment]
Another advantage of re-building the natives on each change could be that we can save a lot of the precious LFS bandwidth. I.e. the bandwidth demand is reduced to a quarter since the three GH workflows don't have to perform a LFS-pull and only the Jenkins build does.

But for the Linux workflow the tests on other platforms fail if the LFS pull is not performed.
On Windows the failure is because the `WebView2Loader.dll` is only available as pointer-file, but for Mac I have to check what's happening. The native compilation step looks quite short.

**Comment by akurtakov** [comment]
We used to keep the this entry in the FAQ https://www.eclipse.org/swt/faq.php#howbuilddll with such instructions.

**Comment by HannesWell** [comment]
> We used to keep the this entry in the FAQ https://www.eclipse.org/swt/faq.php#howbuilddll with such instructions.

Thanks for the reference. It looks like this is (unsurprisingly) somewhat outdated.

At least for the GH-runners `sudo apt-get install libgnomeui-dev libxtst-dev freeglut3-dev libgtk-3-dev libgtk2.0-dev` is not necessary but `sudo apt-get install libgtk-3-dev freeglut3-dev webkit2gtk-driver` is sufficient. But the GH runners have some software preinstalled, thus it does not necessarily mean that the other dependencies are in general obsolete.

**Comment by HannesWell** [comment]
Looking at the logs of the macosx build I have the impression that the native binaries are not properly compiled.
```
[INFO] --- antrun:3.1.0:run (build-native-binaries) @ org.eclipse.swt.cocoa.macosx.x86_64 ---
[INFO] Executing tasks
[INFO]      [exec] Copy 4 native source folders for cocoa.x86_64
[INFO]      [exec] from /Users/runner/work/eclipse.platform.swt/eclipse.platform.swt/bundles/org.eclipse.swt
[INFO]      [exec] to /Users/runner/work/eclipse.platform.swt/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.x86_64/target/natives-build-temp
Warning:       [echo] Compile SWT natives against headers and libraries from JDK: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64/Contents/Home
[INFO]      [exec] 12.7.2
[INFO]      [exec] rm -f *.jnilib *.o
[INFO] Executed tasks
```

Comparing that with the linux logs it seems not much is happening. I believe that's the reason for the failure.

```
[INFO] --- antrun:3.1.0:run (build-native-binaries) @ org.eclipse.swt.gtk.linux.x86_64 ---
[INFO] Executing tasks
[INFO]      [exec] Copy 7 native source folders for gtk.x86_64
[INFO]      [exec] from /home/runner/work/eclipse.platform.swt/eclipse.platform.swt/bundles/org.eclipse.swt
[INFO]      [exec] to /home/runner/work/eclipse.platform.swt/eclipse.platform.swt/binaries/org.eclipse.swt.gtk.linux.x86_64/target/natives-build-temp
Warning:       [echo] Compile SWT natives against headers and libraries from JDK: /usr/lib/jvm/temurin-17-jdk-amd64
[INFO]      [exec] -e Cairo found, compiling SWT support for the cairo graphics library.
[INFO]      [exec] -e jni.h found
[INFO]      [exec] -e libjawt.so found, the SWT/AWT integration library will be compiled.
[INFO]      [exec] -e Building SWT/GTK+ for Architectures: linux x86_64
[INFO]      [exec] -e Building GTK3 bindings:
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror -c swt.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror   -c -o c.o c.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror   -c -o c_stats.o c_stats.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -DUSE_ASSEMBLER -c callback.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-gtk-4964r6.so swt.o c.o c_stats.o callback.o
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c os.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c os_structs.c 
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c os_custom.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c os_stats.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c gtk3.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c gtk3_stats.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gtk+-3.0 gtk+-unix-print-3.0` -c gtk3_structs.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-pi3-gtk-4964r6.so swt.o os.o os_structs.o os_custom.o os_stats.o gtk3.o gtk3_stats.o gtk3_structs.o `pkg-config --libs-only-L gtk+-3.0 gthread-2.0` -L/usr/X11R6/lib64 -L/usr/X11R6/lib -lgtk-3 -lgdk-3 -lcairo -lgthread-2.0
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags atk gtk+-3.0 gtk+-unix-print-3.0` -c atk.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags atk gtk+-3.0 gtk+-unix-print-3.0` -c atk_structs.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags atk gtk+-3.0 gtk+-unix-print-3.0` -c atk_custom.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags atk gtk+-3.0 gtk+-unix-print-3.0` -c atk_stats.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-atk-gtk-4964r6.so swt.o atk.o atk_structs.o atk_custom.o atk_stats.o `pkg-config --libs-only-L atk` -latk-1.0 
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror  -c glx.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror  -c glx_structs.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror  -c glx_stats.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-glx-gtk-4964r6.so swt.o glx.o glx_structs.o glx_stats.o -lGL -lGLU -lm
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gio-2.0` -c webkitgtk.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gio-2.0` -c webkitgtk_structs.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gio-2.0` -c webkitgtk_stats.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags gio-2.0` -c webkitgtk_custom.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-webkit-gtk-4964r6.so swt.o webkitgtk.o webkitgtk_structs.o webkitgtk_stats.o webkitgtk_custom.o `pkg-config --libs-only-l gio-2.0`
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags cairo` -c cairo.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags cairo` -c cairo_structs.c
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror `pkg-config --cflags cairo` -c cairo_stats.c
[INFO]      [exec] gcc -shared -fPIC  -s -o libswt-cairo-gtk-4964r6.so swt.o cairo.o cairo_structs.o cairo_stats.o `pkg-config --libs-only-L cairo` -lcairo
[INFO]      [exec] gcc -O -Wall -fPIC -DSWT_VERSION=4964r6   -DLINUX -DGTK -I/usr/lib/jvm/temurin-17-jdk-amd64/include -I/usr/lib/jvm/temurin-17-jdk-amd64/include/linux -DJNI64 -Werror   -c -o swt_awt.o swt_awt.c
[INFO]      [exec] gcc -shared   -s -o libswt-awt-gtk-4964r6.so swt_awt.o -L/usr/lib/jvm/temurin-17-jdk-amd64/lib -ljawt
[INFO]      [exec] cp libswt-gtk-4964r6.so libswt-awt-gtk-4964r6.so libswt-pi3-gtk-4964r6.so libswt-cairo-gtk-4964r6.so libswt-atk-gtk-4964r6.so libswt-glx-gtk-4964r6.so libswt-webkit-gtk-4964r6.so /home/runner/work/eclipse.platform.swt/eclipse.platform.swt/binaries/org.eclipse.swt.gtk.linux.x86_64
[INFO]      [exec] rm -f *.o *.so
[INFO]      [exec] -e GTK3 Build succeeded
[INFO] Executed tasks
```

**Comment by HannesWell** [comment]
> Comparing that with the linux logs it seems not much is happening. I believe that's the reason for the failure.

I think the reason was that for the mac fragments no make targets were defined in the corresponding `targets` properties. It used to be in the binaries repo like that and was probably forgotten or never used. So this PR already helped to fix things.

Lets see what the build says.

**Comment by HannesWell** [comment]
Great, now all builds passes. 🎉
And looking at the logs, building the native binaries takes a little bit more than 10s for linux and mac and about a minute for Windows. Given the benefit it has, run the tests with up-to-date binaries and a big saving in LFS bandwidth, I think it is worth that little extra time.

**Pull request merged**
