### PR TITLE
[GTK4] Migrate FileDialog to new GTK FileDialog API

### PR DESCRIPTION
**Pull request by ptziegler**
The FileChooser API has been marked as deprecated with GTK 4.10 and replaced by the FileDialog API. With this contribution, this old API has now been limited to GTK3.

Following methods have been added to OS.java:

- g_list_store_new
- g_list_store_append

Following methods have been moved from GTK.java to GTK3.java:

- gtk_file_chooser_add_filter
- gtk_file_chooser_get_filter
- gtk_file_chooser_set_current_name
- gtk_file_chooser_set_filter
- gtk_file_chooser_set_select_multiple
- gtk_file_chooser_native_new

Following constant has been added to GTK.java:

- GTK_TYPE_FILE_FILTER

Following methods have been removed from GTK4.java:

- gtk_file_chooser_get_files
- gtk_file_chooser_get_file
- gtk_file_chooser_set_current_folder
- gtk_file_chooser_set_file

Following methods have been added to GTK4.java:

- gtk_file_dialog_set_initial_name
- gtk_file_dialog_set_initial_file
- gtk_file_dialog_set_title
- gtk_file_dialog_set_default_filter
- gtk_file_dialog_set_filters
- gtk_file_dialog_get_default_filter
- gtk_file_dialog_open_multiple
- gtk_file_dialog_open_multiple_finish
- gtk_file_dialog_open
- gtk_file_dialog_open_finish
- gtk_file_dialog_save
- gtk_file_dialog_save_finish

This commit also amends an oversight from
2e61b4be73c51afe0264028534306fff874e2ea9 where the title of the directory dialog was no longer set.

Contributes to:
https://github.com/eclipse-platform/eclipse.platform.swt/issues/652

### CODE REVIEW

**Comment by ptziegler** [comment]
Open Dialog (GTK3)
OpenDialog_gtk3

Open Dialog (GTK4)
OpenDialog_gtk4

Save Dialog (GTK3)
SaveDialog_gtk3

Save Dialog (GTK4)
SaveDialog_gtk4

**Comment by ptziegler** [comment]
The Mac crash is probably unrelated? And for GTK3, I seem to require a GTK3_LOAD_FUNCTION macro. 

I'm not exactly sure how it plays into GTK, but couldn't I simply copy the macro?

https://github.com/eclipse-platform/eclipse.platform.swt/blob/02e20d69dcddf3567979ebb33ef73f43e3d5fd4b/bundles/org.eclipse.swt/Eclipse%20SWT%20PI/gtk/library/os.h#L44

**Comment by ptziegler** [comment]
I really have no clue what's going on with the Jenkins job...

**Comment by akurtakov** [comment]
Thanks for these much needed steps ahead in the GTK4 port! I'm really overwhelmed with many other tasks (incl. trying to stabilize the releng and tests) thus my reviews are more than slow.

**Comment by ptziegler** [comment]
That's perfectly fine. I understand that the GTK4 doesn't have the highest priority right now, so I really appreciate you still finding the time to have a look at it! 😄

**Comment by akurtakov** [comment]
> That's perfectly fine. I understand that the GTK4 doesn't have the highest priority right now, so I really appreciate you still finding the time to have a look at it! 😄

But it should have the highest priority as this is the future! Thank you for the work and keep the patches coming, I'll do my best to find time for them!

**Comment by laeubi** [comment]
@ptziegler I just tried to compile this on Debian 12 (the current stable LTS release) but it fails with a lot of

```
gtk4.c: In function ‘Java_org_eclipse_swt_internal_gtk4_GTK4_gtk_1file_1dialog_1get_1default_1filter’:
gtk4.c:665:21: error: implicit declaration of function ‘gtk_file_dialog_get_default_filter’; did you mean ‘gtk_window_get_default_size’? [-Werror=implicit-function-declaration]
  665 |         rc = (jlong)gtk_file_dialog_get_default_filter((GtkFileDialog *)arg0);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     gtk_window_get_default_size
gtk4.c:665:57: error: ‘GtkFileDialog’ undeclared (first use in this function); did you mean ‘GtkNativeDialog’?
  665 |         rc = (jlong)gtk_file_dialog_get_default_filter((GtkFileDialog *)arg0);
      |                                                         ^~~~~~~~~~~~~
      |                                                         GtkNativeDialog
```

The reasons seems that the gtk4 version is `4.8.3+ds-2+deb12u1` so this new API seem to raise the barrier quite a lot.

Is there any chance to make it "dynamic" using the new API? Or probably we should even use the old API as long as GTK 4.10 is not widely used?

**Comment by akurtakov** [comment]
Staying on the old API has a price as "portals" are not working (as shown in the screenshots - KDE dialogs not picked up but the default GTK one used). The right step ahead is making the new functions dynamic and making the code:
```
if GTK_VERSION <4.10
    old_api
else
    new_api
```
This is done in many places in SWT already.

**Comment by laeubi** [comment]
I created now
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1519

with some steps in that direction. @ptziegler if you can help here it would be welcome, I just sharing my current attempts in the PR just in case it is useful :-)

**Comment by doronbehar** [comment]
Was this part of the 4.34 release? I'm getting deprecation errors when trying to `make gtk4`.

**Comment by ptziegler** [comment]
> Was this part of the 4.34 release?

Yes.

> I'm getting deprecation errors when trying to make gtk4.

As mentioned in https://github.com/eclipse-platform/eclipse.platform.swt/issues/1653, the errors highly depend on the version of GTK4 you're compiling against. In < 4.10, the build should still succeed (which I believe is what the job ran with) but fails with more recent versions.

**Comment by ptziegler** [comment]
> Thanks for the quick reply. https://github.com/eclipse-platform/eclipse.platform.swt/issues/1653 doesn't present the same build errors I got.

Because you're calling the bash script directly, while the other builds the binaries as part of the Maven job (which internally also calls the bash script). There error doesn't look the same, even though they have the same root cause.

> I also wonder why is https://github.com/eclipse-platform/eclipse.platform.swt/issues/652 still open if this PR was merged. Are there still missing pieces to the GTK4 migration?

Because the GTK4 is not even remotely done. The deprecated API aside, even basic functionality such as `moveAbove()` and `moveBelow()` doesn't work.

**Comment by doronbehar** [comment]
OK thanks for the detailed and very quick response :). Will track #652.

**Comment by laeubi** [comment]
@doronbehar If you can help resolve some of these issues it would be highly appreciated.

**Pull request merged**
