### PR TITLE
Test if incrementing tag suffix with wrap around to az azz fixes build.

### PR DESCRIPTION
**Pull request by the-snowwhite**

### CODE REVIEW

**Comment by akurtakov** [comment]
Honestly I totally dislike the idea of even more javascript in the build scripts. It's a move in the wrong direction IMHO.

**Comment by the-snowwhite** [comment]
Please do not merge this commit as there still are issues to be discussed around it.
https://github.com/eclipse-platform/eclipse.platform.swt/issues/868

**Comment by the-snowwhite** [comment]
replaced by https://github.com/eclipse-platform/eclipse.platform.swt/commit/9a71c28273aa67256979430a38ae0bd2c4140c08

**Comment by the-snowwhite** [comment]
This is a long term solution however it means more java code in the ant build.

**Comment by mickaelistria** [comment]
Like @akurtakov , I think a long term solution must involve simplification, not extra javascript code.
Solution can be to just stop committing or to just suffix with timestamp instead of maintaining a suffix generation algorithm which seems not so necesary.

**Comment by the-snowwhite** [comment]
I agree that simplification is to prefer rather than more java script.
However Why not suffix with commit id's instead of timestamps ?
That said I know nothing about for what reasons the current tag system was implemented and what it's good for
other than the build speedup mentioned in the ant build script.

**Comment by mickaelistria** [comment]
> However Why not suffix with commit id's instead of timestamps ?

timestamps allow version to be comparable and to more easily favor the latest and greatest.

**Comment by the-snowwhite** [comment]
Superseeded by:
https://github.com/eclipse-platform/eclipse.platform.swt/commits/master
https://github.com/eclipse-platform/eclipse.platform.swt/commit/5e283d68b0d92e4a72d1db14a2a5367d9d3dd3bc

**Pull request closed without merging**
