### PR TITLE
Fix Clipboard ImageTransfer not working on Linux x86_64

### PR DESCRIPTION
**Pull request by Phillipus**
- Change value of transferData.format from 32 to 16
- See #146

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@akurtakov , @sravanlakkimsetti, @SyntevoAlex : I'm inclined to merge this PR today so we can get it into **4.24 M3**.

Any objections?

**Comment by iloveeclipse** [comment]
@akurtakov , @sravanlakkimsetti, @SyntevoAlex : I'm inclined to merge this PR today so we can get it into **4.24 M3**.

Any objections?

**Comment by Phillipus** [comment]
@iloveeclipse Do you think we set the value to 8 because of https://github.com/eclipse-platform/eclipse.platform.swt/issues/146#issuecomment-1126800896

**16.3 Supplying the selection** `The format field is actually important here - the X server uses it to figure out whether the data needs to be byte-swapped or not. Usually it will be 8 - i.e. a character - or 32 - i.e. a. integer.`

**Comment by akurtakov** [comment]
No objection from my side. Local test (Fedora 36, Wayland) showed that format=32 makes image (copied from ClipboardExample) to be pasted(in Gimp) partially. format=8 and format=16 work.

**Comment by Phillipus** [comment]
OK, I'll change the value to 8.

What's best practice of PRs? Do I just add another commit on my fork, or something else?

> and document that we simply guess it makes more sense...

Where to do that? In the git commit? In code?

**Comment by Phillipus** [comment]
Forced push the changes now.

Happy to make changes to the comment if needed.

**Review by akurtakov — APPROVED** [review]

**Review by iloveeclipse — APPROVED** [review]
Thank you!

**Comment by Phillipus** [comment]
Thanks for the fast review, feedback and advice!

**Pull request merged**
