### PR TITLE
Bug 577878 - [GTK] Limit Table/Tree drag image to contol's width

### PR DESCRIPTION
**Pull request by SyntevoAlex**
Continuation from https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/192265

### CODE REVIEW

**Comment by SyntevoAlex** [comment]
I still think that this should be merged.

The simplest reason is that cropping the drag image already occurs on Windows and macOS.

The other reason is to avoid super wide drag images, which could easily occur if one column of Table/Tree contains some large string and column auto-sizing is in effect. In this case, drag images for ALL items will be super wide. And super wide drag images could be a usability problem, whereas abrupt content end due to cropping is a marginal beauty problem.

**Comment by mickaelistria** [comment]
Can you please rebase locally and push force to your branch? This should prevent from seeing the version error appearing in CI.

**Comment by SyntevoAlex** [comment]
Unfortunately it still fails with error:
```
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:3.0.0-SNAPSHOT:
compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.swt.tools:
Only qualifier changed for (org.eclipse.swt.tools/3.109.300.v20220329-0614).
Expected to have bigger x.y.z than what is available in baseline (3.109.300.v20211104-1108) -> [Help 1]
```

This commit does not modify `org.eclipse.swt.tools`.
@akurtakov is that a migration bug?

Also, @akurtakov, if you have no objections, I would prefer to merge this patch - see reasoning above.

**Comment by akurtakov** [comment]
According to https://download.eclipse.org/eclipse/downloads/drops4/I20220329-1800/buildlogs/reporeports/reports/versionChecks.html it's an actual check so swt.tools needs version bump. I'll handle it now.

**Comment by akurtakov** [comment]
Let's merge. It's an improvement although not ideal.

**Comment by SyntevoAlex** [comment]
Perfect, thanks!

**Pull request merged**
