### PR TITLE
Enable Tests for GH action

### PR DESCRIPTION
**Pull request by laeubi**
Lets see if we can get the tests running...

### CODE REVIEW

**Comment by laeubi** [comment]
Test can now be run on linux and windows but mac complains:

> ***WARNING: Display must be created on main thread due to Cocoa restrictions. Use vmarg -XstartOnFirstThread

even though the pom seem to already pass that option it seems not be picked up

**Comment by laeubi** [comment]
MacOS Tests are running now but seem been blocked in `Running Test_org_eclipse_swt_browser_Browser#test_stop` by the following message:

> 2022-05-07 16:25:26.446 java[2764:12015] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Use HTTPS instead or add Exception Domains to your app's Info.plist.

can anyone with mac knowledge tell whats wrong here? Do we need additional configuration for macos or should we adjust the tests?

**Comment by laeubi** [comment]
I tried to replace all `http` with `https` in tests now...

**Comment by laeubi** [comment]
Now all verification steps succeed, lets see if it has any impact on the Jenkins CI ...

**Comment by lshanmug** [comment]
> I tried to replace all `http` with `https` in tests now...

On Mac, the Browser does not allowed http now in due to App Transport Security, so we can fix the tests to use https.

**Pull request merged**
