### PR TITLE
Remove unused import in tests

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by SyntevoAlex** [comment]
Right, sorry. IDEA only considers this as low-priority issue.

**Comment by akurtakov** [comment]
> Right, sorry. IDEA only considers this as low-priority issue.

Isn't there smth like "save action" to auto do it ?

**Comment by SyntevoAlex** [comment]
It would be best if GitHub build action also checked that to reject such patches

**Comment by mickaelistria** [comment]
The .settings can probably be set to report such unused import as errors, and tycho would read the settings and fail the compilation in such case

**Pull request merged**
