### PR TITLE
[Build] Remove unused ant tasks and properties

### PR DESCRIPTION
**Pull request by HannesWell**
Assume that natives are only build in the Jenkins pipeline or in a Maven build using `-Dnative=${os}.${ws}.${arch}`.

The "SWT Classpath Builder.launch" is not necessary anymore since Oomph does the same and the .classpath file suitable for the running platform can also be easily selected and renamed manually.
Or @iloveeclipse do you use that launch config or are aware of a wider user base?

Part of https://github.com/eclipse-platform/eclipse.platform.swt/issues/513

### CODE REVIEW

**Comment by iloveeclipse** [comment]
> do you use that launch config or are aware of a wider user base?

I don't think I've intentionally used that at all.
@trancexpress : did you used it?

As far as I can remember, we use shell scripts for natives build. I believe that must be also documented somewhere in the SWT repo.

**Comment by HannesWell** [comment]
I just rechecked it and the `SWT Classpath Builder` launch is mentioned nowhere.

> As far as I can remember, we use shell scripts for natives build. I believe that must be also documented somewhere in the SWT repo.

Do you mean we as Eclipse SWT project or are you referring to your company?
Because currently it is a convoluted mixture of shell-scripts and ant-tasks that are called by maven or groovy directly in the Jenkins to build the natives for all platforms.
But you can also build the binaries only for the running platform via a simple maven build from the swt.binaries repo (or this repo once #956 is completed: `mvn clean verify -Dnative=${ws}.${os}.${arch}`
For windows for example `mvn clean verify -Dnative=win32.win32.x86_64`

**Comment by iloveeclipse** [comment]
@HannesWell : may be I misunderstood your question. I don't use Oomph, so if the deleted launch was there to create proper platform dependent .classpath files, I still need that.

**Comment by HannesWell** [comment]
> @HannesWell : may be I misunderstood your question. I don't use Oomph, so if the deleted launch was there to create proper platform dependent .classpath files, I still need that.

OK, I just checked again what the launch config is actually doing and it is not used to to rename any of the prepared .classpath_${os} files to .classpath but to build org.eclipse.swt_<version>.jar locally using the (also removed) `build.xml` file.
But I checked the result and the content of the jar is very incomplete, e.g. there are no class files and the metadata are also outdated. Since these data are obviously not maintained, I suggest to continue with the removal. One can still build a jar locally with maven.
Sorry for the confusion.

**Comment by HannesWell** [comment]
I'm going to submit this now so that in case of unexpected I-build problems I have time tomorrow to fix them.

**Pull request merged**
