### PR TITLE
Replicate Jenkins build in GH action

### PR DESCRIPTION
**Pull request by akurtakov**
This should make
https://github.com/eclipse-platform/eclipse.platform.swt/issues/251
work.

### CODE REVIEW

**Comment by akurtakov** [comment]
@laeubi @SyntevoAlex Would you please check that this one works for you? The important change is passing -DforceContextQualifier=zzz to swt fragments builds which ensures that they always override the repo one, just like if a version bump has happened. This is also the reason why both repos can't be build with single aggregator build.

**Review by laeubi — APPROVED** [review]
Looks good to me, still wondering why baseline checks are enabled if we effectively disable them afterwards...

**Comment by akurtakov** [comment]
We want them enabled in the aggregator build but not in the verification build.

**Comment by SyntevoAlex** [comment]
I suggest to just merge it and see what happens next. If my unit test #252 will stop finding problems, then I guess we could declare it a victory.

**Comment by laeubi** [comment]
> We want them enabled in the aggregator build but not in the verification build.

Then it should also work to simply disable it for the complete build with `-Dcompare-version-with-baselines.skip=true` then also aggregator build should work as desired.

**Comment by laeubi** [comment]
> I suggest to just merge it and see what happens next.

You can find the results if this right here: https://github.com/eclipse-platform/eclipse.platform.swt/runs/7901664228 I don't see a problem with that test there (what is not surprising because baseline checks are disabled for the first build).

**Comment by SyntevoAlex** [comment]
Going through that link, I see this in logs for Windows Java 11:
```
Warning:  MavenProject: org.eclipse.swt:org.eclipse.swt:3.121.0-SNAPSHOT @ D:\a\eclipse.platform.swt\eclipse.platform.swt\eclipse.platform.swt\bundles\org.eclipse.swt\pom.xml: baseline and build artifacts have same version but different contents
   no-classifier: different
      .api_description: different
      META-INF/p2.inf: different
      about.html: different
      about_files/IJG_README: different

[INFO] MavenProject: org.eclipse.swt:org.eclipse.swt:3.121.0-SNAPSHOT @ D:\a\eclipse.platform.swt\eclipse.platform.swt\eclipse.platform.swt\bundles\org.eclipse.swt\pom.xml
    The main artifact has been replaced with the baseline version.
```

**Comment by SyntevoAlex** [comment]
I don't know what this means, but based on previous discussions, it looks supsicious

**Comment by akurtakov** [comment]
org.eclipse.swt artifact is plain shell, aka it contains nothing so it will be replaced almost always. I'm merging this one if there are issues please reopen.

**Comment by SyntevoAlex** [comment]
OK, thanks for clarification!
@akurtakov thanks for fixing it!

**Pull request merged**
