### PR TITLE
Refactor Image for Readability

### PR DESCRIPTION
**Pull request by amartya4256**
This contribution refactors the Image class to improve readability. The following refactoring have been done:
1. Encapsulating Image metadata, i.e. Handle, width, height and zoom information per zoom level.
2. Abstracting ImageProviders, i.e. ImageDataProvider, ImageFileNameProvider.

contributes to #62 and #127

### CODE REVIEW

**Review by fedejeanne — CHANGES_REQUESTED** [review]
@amartya4256 I made some changes in 2 extra commits so you can review it better. 

Here are my changes:
- Rename AbstractImageProvider to AbstractImageProviderWrapper
- Changed equals implemenation (made it shorter)
- Added Objects.requireNonNull to constructors in subclasses of AbstractImageProviderWrapper
- Changed return type of method createCopy(...) in subclasses

- Remove class StaticZoomUpdater (separate commit)

The part I would like you to check and validate/revert is the one about **adding `Objects.requireNonNull(...)` to constructors** since I can only assume that the `provider`s that the subclasses hold are never `null`. My assumption is merely based on the fact that you didn't check for `null` in the `equals(...)` / `hashCode()` methods in those subclasses, but if you are not sure about this then please add null-checks to those methods and remove `Objects.requireNonNull(...)` from the constructors.

The ball is on your side again and therefore I marked this PR as "changes requested" ;-)

**Comment by amartya4256** [comment]
> @amartya4256 I made some changes in 2 extra commits so you can review it better.
> 
> Here are my changes:
> 
> * Rename AbstractImageProvider to AbstractImageProviderWrapper
> * Changed equals implemenation (made it shorter)
> * Added Objects.requireNonNull to constructors in subclasses of AbstractImageProviderWrapper
> * Changed return type of method createCopy(...) in subclasses
> * Remove class StaticZoomUpdater (separate commit)
> 
> The part I would like you to check and validate/revert is the one about **adding `Objects.requireNonNull(...)` to constructors** since I can only assume that the `provider`s that the subclasses hold are never `null`. My assumption is merely based on the fact that you didn't check for `null` in the `equals(...)` / `hashCode()` methods in those subclasses, but if you are not sure about this then please add null-checks to those methods and remove `Objects.requireNonNull(...)` from the constructors.
> 
> The ball is on your side again and therefore I marked this PR as "changes requested" ;-)

It looks good to go.

**Review by fedejeanne — APPROVED** [review]

**Comment by fedejeanne** [comment]
Ignoring the usual suspects: https://github.com/eclipse-platform/eclipse.platform.swt/issues/1676 and https://github.com/eclipse-platform/eclipse.platform.swt/issues/1564

**Comment by fedejeanne** [comment]
These 2 tests in `Test_org_eclipse_swt_graphics_Image` failed with a NPE in yesterday's I-BUILD:
- `test_ConstructorLorg_eclipse_swt_graphics_Device_ImageDataProvider`
- `test_ConstructorLorg_eclipse_swt_graphics_Device_ImageFileNameProvider`

The exception is:

```java
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:233)
at org.eclipse.swt.graphics.Image$ImageDataProviderWrapper.<init>(Image.java:2114)
at org.eclipse.swt.graphics.Image.<init>(Image.java:592)
...
```

I created a PR to fix them: #1688

**Pull request merged**
