### PR TITLE
Move SWT native binaries in this repository stored in Git LFS

### PR DESCRIPTION
**Pull request by HannesWell**
Configure this Git-repository to store the SWT native binaries, i.e. all *.dll, *.so and *jnilib files, using Git's Large File Storage (LFS) and move the platform-specific SWT fragments from the
eclipse.platform.swt.binaries repository into the binaries folder in this repository.

The platform specific projects are (minimally adjusted) copies of the corresponding projects from
https://github.com/eclipse-platform/eclipse.platform.swt.binaries/tree/9cdcee51a79a3f72e10e074b87326f80d3d6ada2

Only leave out the 'forceQualifier.txt' since the main bundle only drives the qualifier.

Fixes https://github.com/eclipse-platform/eclipse.platform.swt.binaries/issues/2

Pending tasks before this can be submitted:
- [ ] Prepare a PR to clear the master branch of https://github.com/eclipse-platform/eclipse.platform.swt.binaries and add a note that it is effectively archived, similar to for example https://github.com/eclipse-platform/eclipse.platform.runtime. Don't mark the entire repository as archived to allow subsequent maintenance work.
- [x] Prepare a PR for https://github.com/eclipse-platform/eclipse.platform.releng.aggregator to remove the `eclipse.platform.swt.binaries` sub-module and adjust the Jenkins pipeline to perform an lfs-pull for sub-modules.
  - https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1700
- [x] Prepare adjustments of nightly I-Builds to perform lfs-pulls for sub-modules too.
  - Probably done with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1700#issuecomment-1880011656
- [x] Prepare adjustments of documentation about how to set up an SWT workspace in https://www.eclipse.org/swt/git.php.
Remove the task to clone swt.binaries (or at least mention that is not necessary with the latest master so that those that work on older states can still set up a SWT workspace). Mention the requirement for the jgit.lfs plugin.
  - https://github.com/eclipse-platform/www.eclipse.org-swt/pull/11
- [x] Report that LFS usage is ready for submission and ask the EF-IT team to purchase extra LFS storage and bandwith as already discussed in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3076

### CODE REVIEW

**Comment by Phillipus** [comment]
Hi, I'm trying to test this but something is missing.

Usually I import the project at `eclipse.platform.swt/bundles/org.eclipse.swt`, set the right `.classpath` file according to my OS and it finds the binaries in the  `eclipse.platform.swt.binaries` project.

With this change it's not finding the `binaries` folder:

```
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4964r4 in java.library.path: /Users/phillipus/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt-cocoa in java.library.path: /Users/phillipus/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt in java.library.path: /Users/phillipus/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	Can't load library: /Users/phillipus/.swt/lib/macosx/x86_64/libswt-cocoa-4964r4.jnilib
	Can't load library: /Users/phillipus/.swt/lib/macosx/x86_64/libswt-cocoa.jnilib
	Can't load library: /Users/phillipus/.swt/lib/macosx/x86_64/libswt.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:345)
```

Is there something else I need to do?

**Comment by HannesWell** [comment]
> EDIT: sorry for the noise, I needed to also import the binary project. At least I can report that this works!

No problem and thanks for trying this out. I probably have to further adjust the Oomph setup as well and have to check again the move of binary content in the workspace.
One important part is also to install the jgit.lfs plugin (which the setup should do already).

In general there is a lot to adjust, but first I'm focusing on the build.

**Comment by HannesWell** [comment]
After a few more adjustments of the Jenkins pipeline the verification build is now passing.
I'm about to test with a separate test-branch if pushing also works as expected.

I have also looked into the test failure in the GH workflows and it looks like only `org.eclipse.swt.tests.junit.Test_org_eclipse_swt_SWT.test_isLocal` is failing although the signature actually looks ok. But I'll investigate that further.

Furthermore I have now adjusted the Oomph setup to work well with the binaries in this repository. My tests with an (almost) cleared workspace and git repo worked well.

I have now also requested the EF-IT team to install git-lfs on the affected Jenkins instance so that my current work-around to download and install it each time is not necessary anymore:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4119

Furthermore I created a list of task that have to or at least should be prepared before this is submitted in my opening comment.

**Comment by HannesWell** [comment]
> I have also looked into the test failure in the GH workflows and it looks like only `org.eclipse.swt.tests.junit.Test_org_eclipse_swt_SWT.test_isLocal` is failing although the signature actually looks ok. But I'll investigate that further.
> 

These failures now magically vanished.

> After a few more adjustments of the Jenkins pipeline the verification build is now passing. I'm about to test with a separate test-branch if pushing also works as expected.

Pushing worked like a charm and thanks to the EF-Infra team we even already have git-lfs installed on all centOS images, so technically all prerequisites are completed and I will continue to work off the TO-DO list in my initial comment.

**Comment by Phillipus** [comment]
Some user feedback (please let me know if not needed)...

I tested the `test-lfs-pushing` branch:

1. Initialised LFS on my clone of `eclipse.platform.swt` repo with `git lfs install --local`
2. Checked out the `test-lfs-pushing` branch
3. All binary files in the `eclipse.platform.swt/binaries` folder were correct (i.e not SHA pointers)
4. I removed the old `eclipse.platform.swt.binaries/bundles/org.eclipse.swt.cocoa.macosx.x86_64` project from my workspace
5. I imported the new `eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.x86_64` project into my workspace
6. I successfully ran a child Eclipse instance, and my RCP app

The only minor inconvenience is having to do stages 4 and 5 each time when switching between the old and new methods. This is necessary because the binary project names are the same, and you cannot import the new one without first removing the old one from the workspace.

**Comment by Phillipus** [comment]
> The only minor inconvenience is having to do stages 4 and 5 each time when switching between the old and new methods. This is necessary because the binary project names are the same, and you cannot import the new one without first removing the old one from the workspace.

A workaround is to change the project name in the `.project` file for the old binary project in `eclipse.platform.swt.binaries`. For my testing on Mac I renamed the project to `org.eclipse.swt.cocoa.macosx.x86_64_Old`. This way I could have both the old and new binary projects present in my workspace, and I only had to close one or the other, not actually remove/add it from the workspace.

**Comment by HannesWell** [comment]
> Some user feedback (please let me know if not needed)...

Constructive feedback is always welcome and I'm very glad that another person also verifies everything keeps working. :)


> 
> I tested the `test-lfs-pushing` branch:
> 
>     1. Initialised LFS on my clone of `eclipse.platform.swt` repo with `git lfs install --local`

It is good to verify that it also works with git-cli, do you know if many SWT devs work with git from the CLI? If so I think it should be mentioned in the CONTRIBUTING guide that git-lfs is required (altough git for windows has it built in, but it still needs to be installed).

Where I personally put more effort into verifying that LFS also works with EGit/JGit from inside Eclipse.
If EGit is used, all that needs to be done is to install `org.eclipse.jgit.lfs` and to enable Git LFS support globally or only for the swt repos as described in https://github.com/eclipse-egit/egit/wiki/User-Guide#git-lfs-support
For the maximum convenience one `can configure Eclipse to automatically make sure the LFS support is enabled whenever Eclipse starts up.` by enabling in the Preferences under `Version Control (Team) -> Git -> Confirmations and Warnings -> Automatically configure LFS..."`. This is what I have done in SWT's Oomph setup in this commit.

So everybody that uses the Oomph just has to run the setup after changing to the latest master once this is merged and restart and then the next fetch should also do an lfs pull.

> > The only minor inconvenience is having to do stages 4 and 5 each time when switching between the old and new binaries. This is necessary because the binary project names are the same, and you cannot import the new one without first removing the old one from the workspace.
> 
> A workaround is to change the project name in the `.project` file for the old binary project in `eclipse.platform.swt.binaries`.
> 
> For my testing on Mac I renamed the project to `org.eclipse.swt.cocoa.macosx.x86_64_Old`. This way I could have both the old and new binary projects present in my workspace, and I only had to close one or the other, not actually remove/add it from the workspace each time.

That's indeed an inconvenience. Renaming the project's sounds like a good workaround that those that cannot simply rebase their current work on the latest master can apply.
But since I will also prepare a PR for swt.binaries to clear the repo on the master, like it was for example done for https://github.com/eclipse-platform/eclipse.platform.runtime, I think it is not suitable to push that workaround to swt.binaries.
My suggestion would simply be to rebase pending work on the latest master once this is merged. So the transition only needs to be done once. And once the mentioned clear of swt.binaries happend the imported native project will close itself any way automatically and one can just delete it. Unfortunately, in this case, the project is only closed if removed from the originating SCM.

**Comment by Phillipus** [comment]
@HannesWell Thanks for your feedback on my feedback. I'm continuing to test, but now on your PR branch rather than `test-lfs-pushing`

> It is good to verify that it also works with git-cli, do you know if many SWT devs work with git from the CLI? 

I actually use the commercial `SmartGit` app for Eclipse repo git management instead of EGit, but I used the CLI to initialise LFS in this case so as to document how to do it in case other people need to know. I don't use Oomph either, preferring the basic vanilla installation of Eclipse (old habits die hard, Eclipse dev since 2003).

> Renaming the project's sounds like a good workaround that those that cannot simply rebase their current work on the latest master can apply.

I think the main use case for this is when you want to test an older SWT commit pre-LFS.

**Comment by HannesWell** [comment]
> @HannesWell Thanks for your feedback on my feedback. I'm continuing to test, but now on your PR branch rather than `test-lfs-pushing`
> 
:)
Please note that I have just have added another commit to this PR's branch that removes the native binaries from the initial check-in since once this PR is merged it will trigger a re-build of the binaries any way so this commit is just a little bit smaller. This is also the reason why the GH workflows will not pass on this PR, but they passed with the binaries and therefore will pass again as soon as the natives build triggered once this PR is merged is completed.
So it might be better to continue testing on the `test-lfs-pushing` branch.
Unfortunately,  due do some infrastructure issues (https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4124) this branch is currently not updated.

> > It is good to verify that it also works with git-cli, do you know if many SWT devs work with git from the CLI?
> 
> I actually use the commercial `SmartGit` app for Eclipse repo git management instead of EGit, but I used the CLI to initialise LFS in this case so as to document how to do it in case other people need to know. 

Sounds good. Once this PR is merged I will send out a mail to the platform-dev mailing list with these steps to make other developers aware of the change and the steps to keep their workspace working.

> I don't use Oomph either, preferring the basic vanilla installation of Eclipse (old habits die hard, Eclipse dev since 2003).

Oomph is definitely worth a try, it makes many tasks much easier (of course, just like each other powerful tool can cause trouble in rare cases).

> 
> > Renaming the project's sounds like a good workaround that those that cannot simply rebase their current work on the latest master can apply.
> 
> I think the main use case for this is when you want to test an older SWT commit pre-LFS.

Makes sense. With that in mind the site [Using SWT from Git](https://www.eclipse.org/swt/git.php) should be updated to show the new and old way and their requirements.

**Comment by HannesWell** [comment]
@Phillipus I have now created a draft for the SWT doc adjustments resulting from this change, your review is highly appreciated:
https://github.com/eclipse-platform/www.eclipse.org-swt/pull/11

**Comment by HannesWell** [comment]
Regarding the necessary adjustments of o.e.platform.releng.aggregator and for the I-build:

As hoped, git clone automatically also performs a git-lfs pull if git-lfs is installed and the user-global or system `.gitconfig` has git-lfs' clean+smudge filters installed. Because the latter is the case for all centos based docker images since git-lfs has been installed via https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4119, no special adjustments for the I-builds should be necessary and nothing more than https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1700 probably has to be done outside of the SWT repository.


So with that I think everything technical is done or prepared and I can request the additional LFS bandwidth+storage in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3076.

**Comment by HannesWell** [comment]
I also want to mentioned that, at least I was not able to push the native binaries through EGit/JGit as described in https://github.com/eclipse-jgit/jgit/issues/11 (@iloveeclipse maybe you can help with that?).
But since the binaries are usually just build and pushed by Jenkins I don't consider this as a blocker. And if in the future one really needs to push native binaries this can still be done through CGit+git-lfs.

**Comment by HannesWell** [comment]
> So with that I think everything technical is done or prepared and I can request the additional LFS bandwidth+storage in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3076.

The additionally LFS data-pack has been added to eclipse-platform with https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3076#note_1608842.

This is the final test-run that also includes pushing to the test branch `test-lfs-pushing`. As noted in https://github.com/eclipse-platform/eclipse.platform.swt/pull/956#issuecomment-1880050869 the GH workflow failures are expected, but should vanish once the master build has (re) build the binaries. The workflows passed when the binaries where pushed too.

The adjustments in the platform.releng.aggregator for its build and the I-build are also prepared with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1700#issuecomment-1880011656 and git-lfs is installed for all affected build machines, in the `releng`- and `platform`-JIPP as well in the I-build pods: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4119#note_1608547

So is prepared and I think this is ready for submission (once the test-push changes are removed).
@iloveeclipse, @akurtakov are you fine if I continue and submit this and https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1700 as soon as all builds have passed this evening? In case there are any issue I'm available this entire evening and maybe an hour tomorrow morning if there are issues in the I-build. Or should I trigger an I-build even as soon as everything required is merged?

**Comment by iloveeclipse** [comment]
@HannesWell : next SDK build is in 6 hours. 
If you have prepared everything you can try to merge and trigger build immediately, so we will get feedback in 1.5 hours.

**Comment by iloveeclipse** [comment]
One question : SWT natives Job on Jenkins need an update?

**Comment by HannesWell** [comment]
> @HannesWell : next SDK build is in 6 hours. If you have prepared everything you can try to merge and trigger build immediately, so we will get feedback in 1.5 hours.

Yes. We need at least one successful build of this repo's master build once this is merged.
The problem is just that currently the mac-arm64 build machine is occupied:
grafik
And the pipeline is therefore waiting for it.
And there is even one Y and P build waiting for that machine.
Do you think it would be ok, in that case to cancel that waiting job? The last time it took 3,5 hours? I can also later retrigger it.

grafik

**Comment by Phillipus** [comment]
There are about 20 existing PRs in this repo. Should owners be informed that should rebase them on the post-LFS commit when this is done? Otherwise checking out an old PR will require the old binaries project.

**Comment by iloveeclipse** [comment]
I would prefer that all SDK tests on all platforms would complete **before** we switch the SWT build, to have clear baseline we can compare with. Unfortunately we don't have one because the SDK build before was not stable, and we've missed two previous builds too due outage.

**Comment by HannesWell** [comment]
> There are about 20 existing PRs in this repo. Should owners be informed that should rebase them on the post-LFS commit when this is done? Otherwise checking out an old PR will require the old binaries project.

I have already prepared a mail to the platform-dev mailing list informing about this change that also includes the necessary steps to get things working again (with EGit and CLI-Git).
So my suggestion would be to get this landed and fully working as soon as possible and then send out the mail. PRs that are not based on the current master should still work assuming the Jenkins pipeline is executed in the state it was at the PR's commit and since the swt.binaries repo still exists this should still work.
Alternatively we could probably update most of the PRs through the GH web-interface.

**Comment by HannesWell** [comment]
The last build of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1700 confirmed with the latest state of the testing branch of this PR that everything works as expected and since then I just rebased this branch.

This PR is now in the state that can be submitted (i.e. all testing changes are removed).


> I would prefer that all SDK tests on all platforms would complete **before** we switch the SWT build, to have clear baseline we can compare with. Unfortunately we don't have one because the SDK build before was not stable, and we've missed two previous builds too due outage.


The macos-arm build machine will complete its currently running I-build test-job in about 15/20min. So for the I-builds we would have a clear baseline.

There are currently just one (or maybe two, I'm not sure) waiting P/Y build jobs:
grafik

I would just cancel them now and restart once this PR's build has passed. I assume that P/Y builds are not that urgent are they?

**Comment by iloveeclipse** [comment]
> I would just cancel them now and restart once this PR's build has passed. I assume that P/Y builds are not that urgent are they?

I think so, so please cancel.

**Comment by HannesWell** [comment]
> > I would just cancel them now and restart once this PR's build has passed. I assume that P/Y builds are not that urgent are they?
> 
> I think so, so please cancel.

Just canceled both waiting jobs `YPBuilds/job/ep431Y-unit-mac64-java17` and `YPBuilds/job/ep431Y-unit-macM1-java17` after verifying that they both run on the needed `nc1ht-macos11-arm64` machine.

Unfortunately I cannot re-trigger them since the jobs did not even start and Jenkins (probably therefore) didn't record them. But [YPBuilds/job/Y-build-4.31/](https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.31/) will run again tomorrow 16:00UTC and trigger that again. If it is really urgent I can also manually trigger these builds with parameter `buildID=Y20240108-1000`.

**Comment by HannesWell** [comment]
OK, the I-build mac-arm tests completed.
I'm going to submit this now, will then submit the `platform.releng.aggr` changes once the native binaries are re-build and will then trigger another I-build (I would rather get the failures at 8/9 in the evening than at midnight).
I'll keep you updated here.

**Comment by HannesWell** [comment]
The master branch build has completed successfully and the binaries were (re-)build and pushed to the master branch with commit https://github.com/eclipse-platform/eclipse.platform.swt/commit/bb3af9889077c0ad952e0897a211bd1c32e99f93.
All GH-workflows are now passing again as well ✔️.

The PR https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1700 is now ready and I will submit it as soon as the build has succeeded.

**Comment by HannesWell** [comment]
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1700 has been merged and I just triggered [`I-build-4.31#77`](https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/77/).

**Comment by Phillipus** [comment]
I'm trying to check out the latest master and I'm getting an error:

```
git-lfs filter-process
Error downloading object: binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-awt-cocoa-4964r5.jnilib (6f0b5d7): Smudge error: Error downloading binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-awt-cocoa-4964r5.jnilib (6f0b5d7ece96b0a8dc73cc7770b28937ff4c5093b562893d01f553c981125c4c): batch request: missing protocol: ""
```

I've installed LFS already. Are the binaries actually available in LFS?

**Comment by HannesWell** [comment]
> I've installed LFS already. Are the binaries actually available in LFS?

That's strange. 
Yes the binaries are actually available. They have been pulled successfully by the eclipse.platform.releng.aggregator build and I-build. Fetching them in my Eclipse worked for this repository and the eclipse.platform.releng.aggregator repository where the lfs objects were pulled for the swt sub-module worked and a fresh clone using CLI-Git (`git clone https://github.com/eclipse-platform/eclipse.platform.swt.git`) worked as well.
Does a fresh clone works for you?

**Comment by iloveeclipse** [comment]
@HannesWell : assuming everything works (SDK build is done soon), could you share steps needed for existing local repositories to "properly" update from master.

If you mean, egit doesn't work, what command is needed, which (if any) config need to be changed etc.

**Comment by Phillipus** [comment]
> Does a fresh clone works for you?

It was one of those weird things where it was working on one machine but not this particular one. The error occurred when switching commits between pre and post LFS. Then, after lots of re-cloning, re-pulling, etc etc. the problem vanished. Who knows?

But let me say this @HannesWell - you've done a lot of hard work on this, and it works. Thank-you!

**Comment by HannesWell** [comment]
> @HannesWell : assuming everything works (SDK build is done soon), could you share steps needed for existing local repositories to "properly" update from master.
> 

Yes, the I-build just succeeded and I checked the result and the native fragments all look good, all changes are expected (version names, etc.). 🎉 I also updated a few open PRs and they pass or fail the verification as they did before.

Furthermore I have just send an [announcement to the platform-dev mailing](https://www.eclipse.org/lists/platform-dev/msg03951.html) in order to provide the necessary steps to other develpers.

> If you mean, egit doesn't work, what command is needed, which (if any) config need to be changed etc.

Only pushing LFS-objects seems not to work from EGit to Github (see https://github.com/eclipse-jgit/jgit/issues/11, but it might also be GH specific). Fetching works like charm, which is probably the relevant use-case 99% of the time.

In order to conclude this task I have created https://github.com/eclipse-platform/eclipse.platform.swt.binaries/pull/70.
With that I think it is completely done and everything looks good.


> > Does a fresh clone works for you?
> 
> It was one of those weird things where it was working on one machine but not this particular one. The error occurred when switching commits between pre and post LFS. Then, after lots of re-cloning, re-pulling, etc etc. the problem vanished. Who knows?

Strange, but I'm glad it is now working for you. 😃
> 
> But let me say this @HannesWell - you've done a lot of hard work on this, and it works. Thank-you!

It was indeed a lot of work. And thank you for your help in testing this!
A special tanks also to @fredg02 and @heurtematte from the EF-Infra team for their fast help to prepare the CI infrastructure for this.

**Pull request merged**
