### PR TITLE
Add problem matcher to github for api and baseline problems

### PR DESCRIPTION
**Pull request by laeubi**
To help people finding problems without looking at the logs.

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov I think freeze period do not really matter here?

**Comment by akurtakov** [comment]
Yes, this one shouldn't be a problem. It's good practice to hold even such commits just on Thu for the sake of simplicity if we have to run a rebuild to have only single change in the gitlog as otherwise we will have to look what the other one is.

**Comment by laeubi** [comment]
> It's good practice to hold even such commits just on Thu for the sake of simplicity if we have to run a rebuild to have only single change in the gitlog as otherwise we will have to look what the other one is.

Alright I think it would be good if the freeze check could add/update a comment that summarize such things (automatically adding when freeze period ends would be useful as well).

**Comment by akurtakov** [comment]
This one needs manual rebase.

**Pull request closed without merging**
