### PR TITLE
Testing for #337

### PR DESCRIPTION
**Pull request by SyntevoAlex**
Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>

### CODE REVIEW

**Comment by Phillipus** [comment]
Did you close this by mistake?

**Comment by SyntevoAlex** [comment]
No, I closed intentionally so that it doesn't clog maintainer's lists. Afterall it's not something ready to merge.

**Comment by Phillipus** [comment]
Would setting it to a _draft_ PR be better?

**Comment by SyntevoAlex** [comment]
To me, it's good as it is. Can always reopen later.

**Pull request closed without merging**
