### PR TITLE
Revert "Fix warning message on Mac about secure coding not enabled"

### PR DESCRIPTION
**Pull request by Phillipus**
- This can cause a crash to desktop

### CODE REVIEW

**Comment by Phillipus** [comment]
Can someone please commit this revert ASAP. I just had a bad crash to desktop because of this.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000019d4286a0

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [94693]

Application Specific Information:
Secure coding for state restoration requested after it was initialized without. NSApplicationDelegate was probably established too late.

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   AppKit                        	       0x19d4286a0 NSPersistentUIRequiresSecureCoding + 192
1   AppKit                        	       0x19c902d64 -[NSPersistentUIManager flushAllChanges] + 1072
2   AppKit                        	       0x19c902858 -[NSPersistentUIFlushScheduler _performFlush] + 144
3   AppKit                        	       0x19c91a104 __45-[NSPersistentUIFlushScheduler scheduleTimer]_block_invoke + 148
4   AppKit                        	       0x19d2d8c44 ___NSMainRunLoopPerformBlockInModes_block_invoke + 44
5   CoreFoundation                	       0x198f46070 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
6   CoreFoundation                	       0x198f45f84 __CFRunLoopDoBlocks + 356
7   CoreFoundation                	       0x198f45414 __CFRunLoopRun + 2440
8   CoreFoundation                	       0x198f44434 CFRunLoopRunSpecific + 608
9   HIToolbox                     	       0x1a36e819c RunCurrentEventLoopInMode + 292
10  HIToolbox                     	       0x1a36e7fd8 ReceiveNextEventCommon + 648
11  HIToolbox                     	       0x1a36e7d30 _BlockUntilNextEventMatchingListInModeWithFilter + 76
12  AppKit                        	       0x19c7a3d68 _DPSNextEvent + 660
13  AppKit                        	       0x19cf99808 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
```

cc @lshanmug @iloveeclipse @merks

**Comment by Phillipus** [comment]
FYI the original commit that this reverts was from me - https://github.com/eclipse-platform/eclipse.platform.swt/commit/89055b4cf9c4252123d9a165916c506653cd2535 - it seemed to be OK with initial testing. But I've just now had 3 crashes to desktop because of it. There must be a certain sequence of events that triggers it. So this revert really needs to be merged ASAP as it's quite a serious bug.

**Review by lshanmug — APPROVED** [review]

**Comment by lshanmug** [comment]
Thanks @Phillipus for testing. 
From the error looks like setting it in SWT is too late... may be it should be set in launcher.

**Comment by Phillipus** [comment]
> Thanks @Phillipus for testing. From the error looks like setting it in SWT is too late... may be it should be set in launcher.

Yes, you're probably right. But if `-noSplash` option is used, then the launcher does not set it and SWT does set it.

Needs more investigation.

**Comment by Phillipus** [comment]
@lshanmug Thanks for the fast response!

**Comment by laeubi** [comment]
Applications can be launched without the launcher anyways...

**Pull request merged**
