### PR TITLE
Revert single character text caching on Mac GC

### PR DESCRIPTION
**Pull request by Phillipus**
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/631
- This caching was only being used in one case when drawing text of one character on a transparent background
- This means that if the GC is used to draw more than one text string with different foreground colors the cached color is used instead of the new one
- This reverts commit 2a2325b0699615424fc557f8d6db2190dd304048.

### CODE REVIEW

**Comment by lshanmug** [comment]
@Phillipus Will review this early next week. AFAIR the change was made to improve the slow scrolling on Mac text editors. We don't want to bring back the issue.

**Comment by lshanmug** [comment]
@elsazac Can you pls try the PR?

**Comment by Phillipus** [comment]
@lshanmug Thanks. I also made another suggestion in https://github.com/eclipse-platform/eclipse.platform.swt/issues/631#issuecomment-1508377944

**Comment by vogella** [comment]
@sratz could you review / test? This affects GEF-classic and therefore would be nice to get fixed.

**Comment by sratz** [comment]
> I assume @sratz you have a Mac. Let me know if that is not true...

No, I don't have one.

However, according to
https://bugs.eclipse.org/bugs/show_bug.cgi?id=366471#c272
and
https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/92329/
the change 2a2325b0699615424fc557f8d6db2190dd304048 helps significantly when
'Show whitespace characters' is checked, due to all the `·` characters being drawn.

**Comment by Phillipus** [comment]
I'm testing on a Mac Mini M1 and a 2020 MacBook Air Intel with Monterey. I have "show whitespace characters" on and I'm on a 4k monitor. I can't detect any lag when scrolling a large text file (using GC.Java to test).

The original bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=366471 was reported in 2011, and things haven gotten a lot faster on Mac since.

**Comment by sratz** [comment]
No objections then to revert the change.

We can do some tests once the I-Builds are available to see if we notice any performance regressions.

**Comment by vogella** [comment]
AFAICS the test failures are not related. Merging.

**Pull request merged**
