### PR TITLE
WIN: do not query OS lastEventTime for UI Freeze Monitoring #360

### PR DESCRIPTION
**Pull request by jukzi**
getLastEventTime() can be slow on windows and is not needed for UI
Freeze Monitoring

### CODE REVIEW

**Comment by jukzi** [comment]
only unrelated errors from tests that fail anyway

**Comment by vogella** [comment]
Should the same change be done on Linux and Mac?

**Comment by jukzi** [comment]
> Should the same change be done on Linux and Mac?

Probably its not an issue on Linux<:
GTK: getLastEventTime() returns Display.lastEventTime -> fast

cocoa: i don't know
.
However it might better to keep implementations similar to even if it's not a problem on Linux/Mac. 
WDYT?

**Comment by vogella** [comment]
> However it might better to keep implementations similar to even if it's not a problem on Linux/Mac.
WDYT?

Yes, keeping the implementations the same would be good

**Pull request merged**
