### PR TITLE
Configure SWT build scripts for 4.35

### PR DESCRIPTION
**Pull request by deepika-u**
Configure SWT build scripts for 4.35

Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2562

### CODE REVIEW

**Comment by akurtakov** [comment]
@deepika-u https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1618/2/pipeline-graph/ failed. Please investigate.

**Comment by deepika-u** [comment]
I am seeing below text in -> https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1618/2/consoleText

[Pipeline] }
[2024-11-26T08:21:16.732Z] Cancelling nested steps due to timeout

For me this looks like some machine issue, can we resubmit the build if all the machines are up now. Specifically linux ppc64le build is the issue from the log => https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1618/2/pipeline-console/?selected-node=209

**Comment by akurtakov** [comment]
If it's a machine being down please report to https://gitlab.eclipse.org/eclipsefdn/helpdesk

**Comment by MohananRahul** [comment]
> If it's a machine being down please report to https://gitlab.eclipse.org/eclipsefdn/helpdesk

The instances are now up, restarted, and successfully connected.

**Comment by akurtakov** [comment]
Build timedout. Smth is wrong with the machines it looks.

**Comment by deepika-u** [comment]
> @deepika-u https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1618/2/pipeline-graph/ failed. Please investigate.

Now i see pipeline-graph passing, https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1618/5/pipeline-graph/
Does that mean we can go ahead with merging this change?

**Comment by deepika-u** [comment]
Thanks alot.

**Pull request merged**
