### PR TITLE
SWT javadoc bash for 4.27

### PR DESCRIPTION
**Pull request by elsazac**
Fixes: #562

### CODE REVIEW

**Review by niraj-modi — CHANGES_REQUESTED** [review]
JavdocBasher is not 100% correct here.
Changes recommended by it is already present in Display.java of mac.
Hence this particular change should be ignored in manual verification.

This PR should not be merged, as no valid changes required for this release.

**Comment by deepika-u** [comment]
This can be closed now i think.

**Comment by akurtakov** [comment]
As requested.

**Pull request closed without merging**
