### PR TITLE
version bump for Backport 577129 to 4.23 maintenance

### PR DESCRIPTION
**Pull request by deepika-u**
Tracked in
https://github.com/eclipse-platform/eclipse.platform.swt/pull/717

### CODE REVIEW

**Comment by niraj-modi** [comment]
@deepika-u lets not create a PR only for version increment only.
We can increment this version in next back-port opportunity to 4.23
If someone complains about any problem, then only we do version increment specifically.

**Review by niraj-modi — CHANGES_REQUESTED** [review]
@deepika-u 
You need to update all the occurrences of `3.119.0` in SWT source and SWT binaries repos as well for  which you will need to create separate PR on SWT binaries repo.

**Comment by deepika-u** [comment]
pr for swt binary repo => 
https://github.com/eclipse-platform/eclipse.platform.swt.binaries/pull/47

**Review by niraj-modi — APPROVED** [review]
Looks good to me.

**Pull request merged**
