### PR TITLE
Bump SWT bundle versions for 4.33

### PR DESCRIPTION
**Pull request by iloveeclipse**
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2085

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Looks like SWT build hangs in signing native macosx.aarch code:

https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1261/1/pipeline-console/?selected-node=191

image

**Comment by iloveeclipse** [comment]
OK, looks like we are waiting for this mashine https://ci.eclipse.org/releng/computer/nc1ht-macos11-arm64/ that currently runs SDK tests https://ci.eclipse.org/releng/job/AutomatedTests/job/ep433I-unit-mac64-java17/

**Review by HannesWell — APPROVED** [review]
This is the right thing to do and should have been done in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1259

The last verification build failed due to the occasional OOM error. I restarted it hoping it passes this time.

> OK, looks like we (https://ci.eclipse.org/releng/view/SWT%20Natives/) are waiting for this machine https://ci.eclipse.org/releng/computer/nc1ht-macos11-arm64/ that currently runs SDK tests https://ci.eclipse.org/releng/job/AutomatedTests/job/ep433I-unit-mac64-java17/

The jobs in the [SWT natives](https://ci.eclipse.org/releng/view/SWT%20Natives/) view are not used anymore and will be deleted soon: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1060

But your observation about the job waiting for the build machine is correct. The mac native builder is unfortunately over-occupied (hopefully this can be solved soon): https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2005#discussion_r1585605977

**Comment by iloveeclipse** [comment]
The build fails, can you see why?

**Comment by HannesWell** [comment]
> The build fails, can you see why?

I only see these obscure `801 Killed` messages: 
`/home/jenkins/agent/workspace/eclipse.platform.swt_PR-1261/eclipse.platform.swt@tmp/durable-9deab4c8/script.sh.copy: line 2:   801 Killed                  mvn clean verify --batch-mode --threads 1C -V -U -e -DforkCount=0 -Papi-check -Dcompare-version-with-baselines.skip=false -Dorg.eclipse.swt.tests.junit.disable.test_isLocal=true -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true`

The number often varies. I was told that this is an out of memory issue and it happened more often in the past. But I cannot really say why. The api-check was a suspect to cause it, but disabling wasn't the silver bullet to fix it :/
I have now disabled it for the verification build in a replay and also disabled test execution. Maybe we are lucky this time.

**Comment by HannesWell** [comment]
> I have now disabled it for the verification build in a replay and also disabled test execution. Maybe we are lucky this time.

Maven build passed now.
Only the subsequent test-analyzer failed because the test

```
00:13:29.851  Recording test results
00:13:29.946  No test report files were found. Configuration error?
Error when executing always post condition:
```

I suggest to submit this nevertheless to have the natives re-built.

**Comment by iloveeclipse** [comment]
Should we trigger build now, or wait for the nightlyin 3 hours?

**Comment by HannesWell** [comment]
> Should we trigger build now, or wait for the nightlyin 3 hours?

We first have to wait until the master built triggered by submitting this change has passed and the rebuilt natives have been pushed.
I'm currently monitoring the built and will retrigger it without API check if it fails again.

**Comment by merks** [comment]
Thank you both for caring for this !!

**Comment by HannesWell** [comment]
> > Should we trigger build now, or wait for the nightlyin 3 hours?
> 
> We first have to wait until the master built triggered by submitting this change has passed and the rebuilt natives have been pushed.

Once that is done we could trigger an I-build. But I would be fine waiting for it too. I don't know if anyone needs it in the (European) night or will take action if there is again an issue.


> Thank you both for caring for this !!

Your welcome 😃

**Pull request merged**
