### PR TITLE
Fix Color of Toolbar Item on Dark Background

### PR DESCRIPTION
**Pull request by BeckerWdf**
~Fixes:~ Contributes to #1233 (it only fixes the issue for Mac)

### CODE REVIEW

**Comment by BeckerWdf** [comment]
This PR fixes the issue on macOS.

Before this change:
old_dark
old_light

With this change:
new_dark
new_light

**Comment by BeckerWdf** [comment]
For Windows I didn't find a corresponding implementation. Maybe there this triangle is drawn by the native widget library. I don't know.

**Review by fedejeanne — COMMENTED** [review]
@BeckerWdf thank you for the fix for Mac.

I haven't looked at the code but I see that this PR doesn't really fix #1233 but only contributes to it (it only fixes the problem in 1 platform).

Please change the commit text and the description of this PR.

**Review by fedejeanne — DISMISSED** [review]
(see my previous comment)

**Comment by BeckerWdf** [comment]
> @BeckerWdf thank you for the fix for Mac.
> 
> I haven't looked at the code but I see that this PR doesn't really fix #1233 but only contributes to it (it only fixes the problem in 1 platform).
> 
> Please change the commit text and the description of this PR.

Sure. It's only macOS. At least it's a start. @fedejeanne: Wanna help with a fix on Windows or Linux?

**Comment by elsazac** [comment]
I tested this in macOS Sonoma, and the PR looks good visually. I haven't reviewed the code changes, but from a visual perspective, the change looks good.

**Comment by BeckerWdf** [comment]
@niraj-modi: Can you provide help with windows?

**Comment by niraj-modi** [comment]
> @niraj-modi: Can you provide help with windows?

@deepika-u Please evaluate for Windows.

**Comment by deepika-u** [comment]
> > @niraj-modi: Can you provide help with windows?
> 
> @deepika-u Please evaluate for Windows.

Let me check on it.

**Comment by BeckerWdf** [comment]
> [deepika-u](/deepika-u)

@deepika-u: Any news on this topic?

**Comment by BeckerWdf** [comment]
> @BeckerWdf thank you for the fix for Mac.
> 
> I haven't looked at the code but I see that this PR doesn't really fix #1233 but only contributes to it (it only fixes the problem in 1 platform).
> 
> Please change the commit text and the description of this PR.

@fedejeanne  Just did that. Pls. re-review and approve if ok for you.

**Comment by BeckerWdf** [comment]
> I tested this in macOS Sonoma, and the PR looks good visually. I haven't reviewed the code changes, but from a visual perspective, the change looks good.

@elsazac: Can you pls. review the code?

**Comment by fedejeanne** [comment]
> > @BeckerWdf thank you for the fix for Mac.
> > I haven't looked at the code but I see that this PR doesn't really fix #1233 but only contributes to it (it only fixes the problem in 1 platform).
> > Please change the commit text and the description of this PR.
> 
> @fedejeanne Just did that. Pls. re-review and approve if ok for you.

@BeckerWdf  thank you for changing the commit text, I just changed the description of this PR for you :-)

**Comment by BeckerWdf** [comment]
> I just changed the description of this PR for you :-)

Thanks a lot. I overlooked this.

**Comment by elsazac** [comment]
> @elsazac: Can you pls. review the code?

For me, the code changes looks ok, I have tried some snippets as well from Toolbars and the changes looks good on them;

but should we get an opinion from @lshanmug ?

**Comment by BeckerWdf** [comment]
> but should we get an opinion from @lshanmug ?

Sure why not.

**Comment by deepika-u** [comment]
> > [deepika-u](/deepika-u)
> 
> @deepika-u: Any news on this topic?

Hello, i was occupied with another issue so i havent looked into this issue. Will check on it.

**Review by elsazac — APPROVED** [review]

**Pull request merged**
