### PR TITLE
test: https://github.com/eclipse-tycho/tycho/issues/3019

### PR DESCRIPTION
**Pull request by the-snowwhite**
by "placing output.. = bin/" in build.properties

This commit seems to do no difference to the maven test build as expected.
But makes it possible to see if the step:
`ant -f eclipse.platform.swt/bundles/org.eclipse.swt/buildSWT.xml tag_projects`
builds correctly afterwards in:
https://github.com/eclipse-platform/eclipse.platform.swt/pull/865
https://github.com/eclipse-platform/eclipse.platform.swt/pull/863

### CODE REVIEW

**Comment by the-snowwhite** [comment]
This doesn't seem to be the solution as:
`ant -f eclipse.platform.swt/bundles/org.eclipse.swt/buildSWT.xml tag_projects`
still fails with:

    06:29:43  BUILD FAILED
    06:29:43  /home/jenkins/agent/workspace/eclipse.platform.swt_PR-867/eclipse.platform.swt/bundles/org.eclipse.swt/buildSWT.xml:309: Unable to determine new tag

**Comment by iloveeclipse** [comment]
Could you please revert your recent change and force push here, to see if that fixes the build?

**Comment by the-snowwhite** [comment]
Got the same failure
So the next logical step in this test would be to revert:
https://github.com/eclipse-platform/eclipse.platform.swt/pull/862
and
https://github.com/eclipse-platform/eclipse.platform.swt/pull/866
ok ?

**Comment by akurtakov** [comment]
My feeling is that the build scripts can't go beyond the "z" for new tags. Last one is https://github.com/eclipse-platform/eclipse.platform.swt/releases/tag/v4963r3z so this build failure has nothing to do with reverting and appying patches.

**Comment by laeubi** [comment]
The mentioned bug is only relevant for **Tycho Api Tools Check** how is it supposed to fix any **Custom Ant Build Scripts**? It would really help to try understand the failure instead of blaming everything on random Tycho issues.

**Comment by the-snowwhite** [comment]
As it does not make sense to revert a commit inside same commit I do not test reverting this commit here.
Anyway I this this PR has made its point so I have created an issue instead:
https://github.com/eclipse-platform/eclipse.platform.swt/issues/868
I close this PR now.

**Pull request closed without merging**
