### PR TITLE
Bump org.eclipse.swt version due to new API

### PR DESCRIPTION
**Pull request by HeikoKlare**
Follow-up for #785.

### CODE REVIEW

**Comment by laeubi** [comment]
@HeikoKlare I suspect this now causes the build to fail see:

https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/45/console

It might be that a bump in swt also needs bumps in the fragments here:

https://github.com/eclipse-platform/eclipse.platform.swt.binaries/blob/master/bundles/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF

@akurtakov can you probably advice here? I can check if I can make Tycho more patient here (as the fragment still matches the range) but wonder what was the general contract here in the past.

**Comment by laeubi** [comment]
I have now further checked this and it is indeed the problem [with this p2.inf](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/META-INF/p2.inf) the fragment is pulled but needs the strict version:

https://github.com/eclipse-platform/eclipse.platform.swt/blob/f19db1416d82929923ffc3dd37ed1b03e522d4f8/bundles/org.eclipse.swt/META-INF/p2.inf#L10

so now this no longer matches what leads to the problem it not found anymore for the consumers (jface), so version bumps are required for all fragments as well!

**Comment by iloveeclipse** [comment]
> might be that a bump in swt also needs bumps in the fragments here

Yes.

**Comment by HeikoKlare** [comment]
@laeubi Thanks for fixing the fragments versions. It would be nice to have an automated check for this implicit constraint. Maybe it will become easier to have that once the fragments are part of this repo: eclipse-platform/eclipse.platform.swt.binaries#2

**Pull request merged**
