### PR TITLE
Issue #462 - [GTK] Rare JVM crash when shutting down OS

### PR DESCRIPTION
**Pull request by SyntevoAlex**

### CODE REVIEW

**Review by akurtakov — APPROVED** [review]
The changes look just fine to me.

**Comment by akurtakov** [comment]
Yes

**Comment by iloveeclipse** [comment]
So let's merge.

**Comment by akurtakov** [comment]
Oops, sorry about that I thought I merged it when I wrote yes.

**Comment by SyntevoAlex** [comment]
Thanks for handling it!

**Pull request merged**
