### PR TITLE
Wayland qt paste fix

### PR DESCRIPTION
**Pull request by the-snowwhite**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Seems like an empty PR to me.

**Comment by the-snowwhite** [comment]
@mickaelistria 
This is a recommit of an allread merged PR to get the build system updated.
I had to add a cosmetic deletion of an surplus line to be able to push the pr which is why it seems empty.
https://github.com/eclipse-platform/eclipse.platform.swt/issues/868#issuecomment-1804185376

**Comment by mickaelistria** [comment]
What issue is it expected to fix? The current state seems good to me.

**Comment by the-snowwhite** [comment]
Well this current state is something I as a new Eclipse contributor can understand.
https://ci.eclipse.org/releng/job/eclipse.platform.swt/view/change-requests/
according to that page now this is the latest successful build. I get pointed to.
From the github web ui.
Looking at open and closed pullrequests I'm also pointed to this PR as the latest correctly created sucessfull pr.
https://github.com/eclipse-platform/eclipse.platform.swt/pulls
The issue this pr fixes is that the pr correcting the build flow was inappropriately committed and merged to master by mistake. 
Instead of  being pushed to a fork and the created via the correct specified method as a normal PR request

**Comment by the-snowwhite** [comment]
@mickaelistria 
https://github.com/eclipse-platform/eclipse.platform.swt/issues/868#issuecomment-1803621585
This is the Issue merging of this PR is supposed to remedy/fix.

>I have pushed in the wrong branch and PR and merge and etc. - Hopefully the fix/workaround is https://github.com/eclipse-platform/eclipse.platform.swt/commit/9a71c28273aa67256979430a38ae0bd2c4140c08 and https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/275/ will show whether this is the case or not, let's give it sometime

**Comment by the-snowwhite** [comment]
@mickaelistria 
the commit list of this pr still shows the original commits in the reopened original branch for the PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/874/commits

**Comment by iloveeclipse** [comment]
@the-snowwhite : please look at commits on master:

https://github.com/eclipse-platform/eclipse.platform.swt/commits/master

Nothing to do here, closikg.

**Pull request closed without merging**
