### PR TITLE
[test] add Test for expand of invisible TreeItem #901

### PR DESCRIPTION
**Pull request by jukzi**
fails on GTK
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1331#issuecomment-1841423291

### CODE REVIEW

**Comment by iloveeclipse** [comment]
> ```
> java.lang.ClassNotFoundException: com.atlassian.clover.recorder.junit.JUnitTestRunnerInterceptor
> Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
> Error:  java.lang.ClassNotFoundException: com.atlassian.clover.recorder.junit.JUnitTestRunnerInterceptor
> Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:631)
> Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
> Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
> Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1240)
> Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1089)
> Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:905)
> Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
> ```

@basilevs :  **where** do you see it, link?
Looks like this can cause SDK build fails too (SWT tests aren't executed ).

**Comment by basilevs** [comment]
> **where** do you see it, link?
https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/7111071900/job/19358535698?pr=933

**Comment by jukzi** [comment]
That JUnitTestRunnerInterceptor was introduced with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1630

Does it only make problem with swt? @akurtakov

**Comment by akurtakov** [comment]
I think what's missing is a dependency to this one being added in the surefire configuration (dependency tag), otherwise it would simply not be downloaded in builds and thus fail that way. TBH, I'm not 100% sure this is the correct way to support parametrized tests but as I don't have the time to investigate it further I don't want to spoil the party. 
For the record I believe this config will fail many different builds.

**Comment by jukzi** [comment]
@SyntevoAlex here is a reproducer you asked for:
 https://github.com/eclipse-platform/eclipse.platform.ui/issues/1331#issuecomment-1838602508_
```
java.lang.AssertionError
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_widgets_Tree.test_persistExpandStatusForInvisibleItems(Test_org_eclipse_swt_widgets_Tree.java:1219)

```

**Comment by SyntevoAlex** [comment]
Unfortunately my queue is more that full currently.
I hope to find time to have a look at this within a few weeks.

**Comment by SyntevoAlex** [comment]
@jukzi you might want to learn how to debug native code. I could give a few hints.

**Comment by jukzi** [comment]
> @jukzi you might want to learn how to debug native code. I could give a few hints.

i would love to if i had the time - same issue here, i can't become expert in every field.

**Comment by jukzi** [comment]
i close this PR as there is currently not enough resources on SWT to fix the behaviour

**Pull request closed without merging**
