### PR TITLE
Fix app name not shown in main menu on macOS Sonoma

### PR DESCRIPTION
**Pull request by Phillipus**
- We need to set the sub-menu to the application name
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/779

### CODE REVIEW

**Comment by Phillipus** [comment]
I've tested that this fixes the problem on macOS Sonoma (14) and also that it does not cause any regressions on macOS Ventura (13).

It seems that Apple changed something regarding menus in Sonoma. The sub-menu now also needs to be explicitly set to the application name.

**Comment by tmssngr** [comment]
I've tried on macOS 14 (no beta tag any more after the latest update) on my Mac Mini M1 and it works fine. Thanks for the fix, @Phillipus!

**Comment by Phillipus** [comment]
> I've tried on macOS 14 (no beta tag any more after the latest update) on my Mac Mini M1 and it works fine. Thanks for the fix, @Phillipus!

Thanks @tmssngr. I see that Syntevo have integrated the fix into the preview build 14 of SmartGit 23.1. It would be good to get this PR committed in time for Eclipse 4.30 (I am not a committer).

**Comment by tmssngr** [comment]
We maintain our own clone of SWT with a couple of fixes/changes: https://github.com/syntevo/eclipse.platform.swt/tree/smartgit-23.1 - that way we don't have to wait for the Eclipse team integrating fixes, or have own fixes/changes that would be rejected.

**Comment by akurtakov** [comment]
@Phillipus I think you're one of the most knowledgable and active contributors when we speak about Cocoa details so I find it weird that you're nominated as a committer yet. Are you interested in becoming one? Help on Mac side is quite badly needed and as long as many of the people actively looking at SWT don't even have Mac's it's a problem merging patches that we can't test.

**Comment by Phillipus** [comment]
> @Phillipus I think you're one of the most knowledgable and active contributors when we speak about Cocoa details so I find it weird that you're nominated as a committer yet. Are you interested in becoming one? Help on Mac side is quite badly needed and as long as many of the people actively looking at SWT don't even have Mac's it's a problem merging patches that we can't test.

Well, I'm not as experienced as say @SyntevoAlex or @lshanmug  when it comes to Mac but I am set up with several Macs and macOS versions so it might make sense to be.a committer for these cases.

**Comment by akurtakov** [comment]
Is this urgent thing to merge ? It looks "safe" but still I don't feel it's right for me to merge it.

**Comment by SyntevoAlex** [comment]
I hope to get my hands on Sonoma soon(tm).
But if anyone else is able to test/approve, don't wait for me!

**Comment by akurtakov** [comment]
@Phillipus Your nomination is up https://projects.eclipse.org/projects/eclipse.platform/elections/election-phil-beauvoir-committer-eclipse-platform

**Comment by tmssngr** [comment]
The latest SmartGit 23.1 preview contains this fix and we haven't received any regression so far. IMHO it is save to merge. At the end, this change is very small.

**Comment by akurtakov** [comment]
merging as per @tmssngr comment.

**Comment by Phillipus** [comment]
Thanks, all.

**Comment by Phillipus** [comment]
It turns out that macOS Sonoma 14.1 (23B73) fixes the underlying issue. The patch is not needed, but there are no side-effects to keeping it and, who knows, the issue might re-appear in a future version of macOS.

**Pull request merged**
