### PR TITLE
Issue #333 - [win32] Revert Tree.setItemCount optimizations

### PR DESCRIPTION
**Pull request by SyntevoAlex**
Reverts code changes from commits:
* 17b40247 - Initial patch that optimizes Tree.setItemCount
* d5270df6 - followup that fixes some regressions in 17b40247

New code comments and snippets are preserved.

The revert is to let Eclipse release safely, a better optimization
attempt will be prepared later.

Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>

### CODE REVIEW

**Comment by Phillipus** [comment]
Is this a full revert? I can only see minimal revert changes to the `Tree` class. Unless I am mistaken?

**Comment by Phillipus** [comment]
I did a quick test in a child Eclipse instance with this PR and can confirm that https://github.com/eclipse-platform/eclipse.platform.swt/issues/333 is not happening.

**Comment by SyntevoAlex** [comment]
I so far tested
* Snippet `Issue0287_Tree_indexOf_Negative`
* Snippet `Bug575787_Tree_SetItemCount_Perf`
* Issue #287

**Comment by mickaelistria** [comment]
Thank you for this revert!

**Comment by SyntevoAlex** [comment]
I did not revert `TVGN_ROOT` changes, probably there's no need.

**Review by niraj-modi — APPROVED** [review]
This patch reverts all the Tree optimization related code changes from Bug 575787 and followup regression fix for issue #287.

IMO, we should be good for RC1 now.

**Comment by vogella** [comment]
Thanks @SyntevoAlex for the fast reaction. Will test in tomorrows I-Build again.

**Pull request merged**
