### PR TITLE
Adjust line dashes on hi-dpi device

### PR DESCRIPTION
**Pull request by Phillipus**
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/687

### CODE REVIEW

**Review by HeikoKlare — COMMENTED** [review]
Thanks for that HiDPI scaling improvement!
From what I have tested so far, the fix works quite well. I have two remarks:
1. I would propose to improve the scaling calculation as mentioned in the detailed comments to avoid unnecessary computation. That also fixes one unnecessary source of rounding error. And it also allows to completely remove the `DPIUtil` extensions.
2. Shouldn't the `getLineDashes()` method also be adapted? The analogous `getLineWidth()` method also scales down the value. I would expect that the following is true, but is is not: `gc.setLineDash(gc.getLineDash()).equals(gc.getLineDash())`. You can also see this when testing the `CTable` with dashes applied to the underlying GC. You can reproduce it with the following initialization added to the snipped given in the associated issue #687.

```java
CTable table = new CTable(shell, SWT.BORDER) {
	@Override
	void onPaint(org.eclipse.swt.widgets.Event event) {
		event.gc.setLineDash(new int[] { 3 });
		super.onPaint(event);
	};
};
table.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true));
table.setLinesVisible(true);
for (int col = 0; col < 3; col++) {
	CTableColumn column = new CTableColumn(table, SWT.NONE);
	column.setWidth(50);
}
```

**Comment by Phillipus** [comment]
@HeikoKlare That's a lot to process. Would it be better if you created a PR?

**Comment by HeikoKlare** [comment]
@Phillipus If you like, I can also provide a PR. Since you did the initial work for the improvement, I just wanted to give feedback to improve the PR, but I can also propose the changes as a whole in a separate PR. Just let me know.

**Review by HeikoKlare — APPROVED** [review]
Thanks for incorporating the suggestions, @Phillipus! From my side, the changes look good now and in my manual tests they have worked as expected.

Since the `GC` class is lacking tests, I have proposed the addition of some tests in #786, which also includes tests that serve as regression tests for this PR (in particular the symmetry of the get and set functions).

**Pull request merged**
