### PR TITLE
ToolItem with SWT.CHECK is not well displayed when checked and with background setted.

### PR DESCRIPTION
**Pull request by RoiSoleil**
ToolItem with SWT.CHECK is not well displayed when checked and with background setted.

Fix : https://github.com/eclipse-platform/eclipse.platform.swt/issues/541

### CODE REVIEW

**Comment by RoiSoleil** [comment]
Failing tests doesn't seems to be related to my PR.

**Comment by vogella** [comment]
@SyntevoAlex could you review?

**Comment by mickaelistria** [comment]
@RoiSoleil in Eclipse project, we try to avoid merge commits. Please prefer rebasing as much as possible.

**Comment by RoiSoleil** [comment]
> @RoiSoleil in Eclipse project, we try to avoid merge commits. Please prefer rebasing as much as possible.

@mickaelistria it should be ok now.

**Comment by RoiSoleil** [comment]
Can someone review this change for Windows ?

@HannesWell @iloveeclipse @niraj-modi

**Comment by deepika-u** [comment]
I am seeing 3 issues as listed below :

Before the fix, i am seeing this way =>
swt check_before_fix

After the fix, i am seeing this way =>
swt check_after_fix


So the fix looks fine for me on dark theme on windows 11.

**Comment by RoiSoleil** [comment]
@vogella In Windows 10, i get this :

image

If in Windows 11, it's not good, i think it should be fixed in another specific issue ... (I'm not sure this is an actual issue)

**Comment by deepika-u** [comment]
> > @deepika-u Thx for the test. This is exactly what i wanted to fix.
> 
> The white background of the sync icon in the package explorer looks bad. It this intended?

@vogella 
To be more specific on your query i see a consistency across this icon and other icons after the fix. This looks to be an obvious behavior for me.

The complete left set of icons are when hovered(abit whitish comparitively).
The complete right set of icons are when they are selected/enabled actually(abit bluish comparitively).
Again both look abit different and also wanted to point out that difference too(in the orange circle - you can make out that difference when same icon is selected.)

For your reference => 
swt check_after_fix_more_similar_icons

Please let me know if that clarifies. Thanks.

**Comment by deepika-u** [comment]
> @vogella In Windows 10, i get this :
> 
> image
> 
> If in Windows 11, it's not good, i think it should be fixed in another specific issue ... (I'm not sure this is an actual issue)

I have no clue on this issue.

**Comment by RoiSoleil** [comment]
> > @vogella In Windows 10, i get this :
> > image
> > If in Windows 11, it's not good, i think it should be fixed in another specific issue ... (I'm not sure this is an actual issue)
> 
> I have no clue on this issue.

It's Windows version specific (difference between Windows 10 and 11), It's another problem for me (I'm not sure this is an actual issue).

**Comment by RoiSoleil** [comment]
@vogella Any news ?

**Review by deepika-u — COMMENTED** [review]
My vote goes to the fix.

**Comment by RoiSoleil** [comment]
@vogella @iloveeclipse @niraj-modi Tested on my personal Eclipse with the fix for 2 months and everything is good. Could you take à look ?

**Comment by vogella** [comment]
@SyntevoAlex could you test?

**Comment by RoiSoleil** [comment]
> @SyntevoAlex could you test?

@SyntevoAlex @vogella any news ?

**Comment by merks** [comment]
Pulling this into my workspace leaves a sea of errors and I'm unable to launch.   I think this needs to be squashed and rebased on master because for master the SWT version is 3.124.0 and this PR reduces that number.

Probably easiest if you switch to master, make sure it's pulled to the latest, apply these two changes, and force push your branch....

**Review by niraj-modi — APPROVED** [review]
Code change LGTM.
Thanks @deepika-u @merks @RoiSoleil for verifying this PR.

**Comment by RoiSoleil** [comment]
Nice !

**Comment by deepika-u** [comment]
Verified this on below build and looks good to me.

Eclipse SDK
Version: 2023-06 (4.28)
Build id: I20230515-1800
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.6+10
Java version: 17.0.6

**Pull request merged**
