### PR TITLE
Remove dead code in `ImageData`

### PR DESCRIPTION
**Pull request by SyntevoAlex**
I wanted to add another image format to SWT and was scared by lots and lots of rather arcane code to fix.
But then I noticed that a lot of that code is in fact dead. This PR cleans it up.

It's split into multiple commits - otherwise it won't be possible to review it with any kind of confidence.

### CODE REVIEW

**Comment by SyntevoAlex** [comment]
@iloveeclipse @niraj-modi @lshanmug would you review?

**Comment by iloveeclipse** [comment]
I haven't managed to review even the first commit, but starting IDE in debugger with this PR applied on top of SWT on Linux I see endless number of exceptions below (I have opened Java editor):
```
java.lang.ArrayIndexOutOfBoundsException: Index 17856 out of bounds for length 17856
	at org.eclipse.swt.graphics.ImageData.blit(ImageData.java:2383)
	at org.eclipse.swt.graphics.Image.init(Image.java:1311)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:418)
	at org.eclipse.ui.texteditor.DefaultRangeIndicator.createImage(DefaultRangeIndicator.java:151)
	at org.eclipse.ui.texteditor.DefaultRangeIndicator.getImage(DefaultRangeIndicator.java:105)
	at org.eclipse.ui.texteditor.DefaultRangeIndicator.paint(DefaultRangeIndicator.java:81)
	at org.eclipse.ui.texteditor.DefaultMarkerAnnotationAccess.paint(DefaultMarkerAnnotationAccess.java:260)
	at org.eclipse.jface.text.source.AnnotationRulerColumn.doPaint1(AnnotationRulerColumn.java:809)
	at org.eclipse.jface.text.source.AnnotationRulerColumn.doubleBufferPaint(AnnotationRulerColumn.java:546)
	at org.eclipse.jface.text.source.AnnotationRulerColumn.lambda$1(AnnotationRulerColumn.java:274)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3882)
	at org.eclipse.swt.widgets.Scrollable.gtk_draw(Scrollable.java:365)
	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:496)
	at org.eclipse.swt.widgets.Canvas.gtk_draw(Canvas.java:174)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2409)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6832)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6114)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1552)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4474)
```

**Comment by SyntevoAlex** [comment]
Thanks! Somehow this mistake has dodged my testing in snippet, our product and unit tests. Also, Eclipse 2022-03 starts fine for me. Anyways, I think I know where the mistake is. I'll fix it soon.

**Comment by SyntevoAlex** [comment]
Should be good now, please continue reviewing.

**Review by niraj-modi — COMMENTED** [review]
Update from Windows till now:
- I couldn't find anything breaking with the latest patch in my testing.. Eclipse self-hosted mode also works fine with this patch.

If nothing breaking seen with this patch, suggest we merge the patch in master early next week, so that we get enough time to test the changes directly in Eclipse build.
Note: next week is last week of development for M1

**Comment by SyntevoAlex** [comment]
Lets merge it, then? Again, I suggest to use rebase-merge instead of squash-merge.

**Review by niraj-modi — APPROVED** [review]
If no objections from others we can merge:
- I am Ok to rebase and merge.

**Comment by SyntevoAlex** [comment]
Thanks for handling it!

**Pull request merged**
